/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  HTTPValidationError,
  OAuthLoginRequest,
  RefreshTokenRequest,
  SessionExchangeRequest,
  TokenResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * OAuth login endpoint.

Verify OAuth token, create/update user, and issue JWE tokens.
 * @summary Login
 */
export const useLoginApiAuthLoginPostHook = () => {
        const loginApiAuthLoginPost = useCustomInstance<TokenResponse>();

        return useCallback((
    oAuthLoginRequest: OAuthLoginRequest,
 signal?: AbortSignal
) => {
        return loginApiAuthLoginPost(
          {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: oAuthLoginRequest, signal
    },
          );
        }, [loginApiAuthLoginPost])
      }



export const useLoginApiAuthLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>, TError,{data: OAuthLoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>, TError,{data: OAuthLoginRequest}, TContext> => {

const mutationKey = ['loginApiAuthLoginPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const loginApiAuthLoginPost =  useLoginApiAuthLoginPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>, {data: OAuthLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginApiAuthLoginPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginApiAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>>
    export type LoginApiAuthLoginPostMutationBody = OAuthLoginRequest
    export type LoginApiAuthLoginPostMutationError = HTTPValidationError

    /**
 * @summary Login
 */
export const useLoginApiAuthLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>, TError,{data: OAuthLoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>,
        TError,
        {data: OAuthLoginRequest},
        TContext
      > => {
      return useMutation(useLoginApiAuthLoginPostMutationOptions(options), queryClient);
    }
    /**
 * Exchange better-auth session token for backend JWE tokens.

Used by email/password auth users who have no OAuth provider token.
Verifies session with better-auth server, then issues backend tokens.
 * @summary Session Exchange
 */
export const useSessionExchangeApiAuthSessionExchangePostHook = () => {
        const sessionExchangeApiAuthSessionExchangePost = useCustomInstance<TokenResponse>();

        return useCallback((
    sessionExchangeRequest: SessionExchangeRequest,
 signal?: AbortSignal
) => {
        return sessionExchangeApiAuthSessionExchangePost(
          {url: `/api/auth/session-exchange`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sessionExchangeRequest, signal
    },
          );
        }, [sessionExchangeApiAuthSessionExchangePost])
      }



export const useSessionExchangeApiAuthSessionExchangePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSessionExchangeApiAuthSessionExchangePostHook>>>, TError,{data: SessionExchangeRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSessionExchangeApiAuthSessionExchangePostHook>>>, TError,{data: SessionExchangeRequest}, TContext> => {

const mutationKey = ['sessionExchangeApiAuthSessionExchangePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const sessionExchangeApiAuthSessionExchangePost =  useSessionExchangeApiAuthSessionExchangePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useSessionExchangeApiAuthSessionExchangePostHook>>>, {data: SessionExchangeRequest}> = (props) => {
          const {data} = props ?? {};

          return  sessionExchangeApiAuthSessionExchangePost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SessionExchangeApiAuthSessionExchangePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSessionExchangeApiAuthSessionExchangePostHook>>>>
    export type SessionExchangeApiAuthSessionExchangePostMutationBody = SessionExchangeRequest
    export type SessionExchangeApiAuthSessionExchangePostMutationError = HTTPValidationError

    /**
 * @summary Session Exchange
 */
export const useSessionExchangeApiAuthSessionExchangePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSessionExchangeApiAuthSessionExchangePostHook>>>, TError,{data: SessionExchangeRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useSessionExchangeApiAuthSessionExchangePostHook>>>,
        TError,
        {data: SessionExchangeRequest},
        TContext
      > => {
      return useMutation(useSessionExchangeApiAuthSessionExchangePostMutationOptions(options), queryClient);
    }
    /**
 * Refresh access token using refresh token.
 * @summary Refresh Token
 */
export const useRefreshTokenApiAuthRefreshPostHook = () => {
        const refreshTokenApiAuthRefreshPost = useCustomInstance<TokenResponse>();

        return useCallback((
    refreshTokenRequest: RefreshTokenRequest,
 signal?: AbortSignal
) => {
        return refreshTokenApiAuthRefreshPost(
          {url: `/api/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenRequest, signal
    },
          );
        }, [refreshTokenApiAuthRefreshPost])
      }



export const useRefreshTokenApiAuthRefreshPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, TError,{data: RefreshTokenRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, TError,{data: RefreshTokenRequest}, TContext> => {

const mutationKey = ['refreshTokenApiAuthRefreshPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const refreshTokenApiAuthRefreshPost =  useRefreshTokenApiAuthRefreshPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, {data: RefreshTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  refreshTokenApiAuthRefreshPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenApiAuthRefreshPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>>
    export type RefreshTokenApiAuthRefreshPostMutationBody = RefreshTokenRequest
    export type RefreshTokenApiAuthRefreshPostMutationError = HTTPValidationError

    /**
 * @summary Refresh Token
 */
export const useRefreshTokenApiAuthRefreshPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, TError,{data: RefreshTokenRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>,
        TError,
        {data: RefreshTokenRequest},
        TContext
      > => {
      return useMutation(useRefreshTokenApiAuthRefreshPostMutationOptions(options), queryClient);
    }
    /**
 * Logout endpoint.

Client should remove tokens from localStorage.
 * @summary Logout
 */
export const useLogoutApiAuthLogoutPostHook = () => {
        const logoutApiAuthLogoutPost = useCustomInstance<void>();

        return useCallback((

 signal?: AbortSignal
) => {
        return logoutApiAuthLogoutPost(
          {url: `/api/auth/logout`, method: 'POST', signal
    },
          );
        }, [logoutApiAuthLogoutPost])
      }



export const useLogoutApiAuthLogoutPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, TError,void, TContext> => {

const mutationKey = ['logoutApiAuthLogoutPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const logoutApiAuthLogoutPost =  useLogoutApiAuthLogoutPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, void> = () => {


          return  logoutApiAuthLogoutPost()
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutApiAuthLogoutPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>>

    export type LogoutApiAuthLogoutPostMutationError = unknown

    /**
 * @summary Logout
 */
export const useLogoutApiAuthLogoutPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(useLogoutApiAuthLogoutPostMutationOptions(options), queryClient);
    }
