/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  EmailLoginRequest,
  HTTPValidationError,
  OAuthLoginRequest,
  RefreshTokenRequest,
  RegisterRequest,
  TokenResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * Register a new user with email and password.
 * @summary Register
 */
export const useRegisterApiAuthRegisterPostHook = () => {
        const registerApiAuthRegisterPost = useCustomInstance<TokenResponse>();

        return useCallback((
    registerRequest: RegisterRequest,
 signal?: AbortSignal
) => {
        return registerApiAuthRegisterPost(
          {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest, signal
    },
          );
        }, [registerApiAuthRegisterPost])
      }



export const useRegisterApiAuthRegisterPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>, TError,{data: RegisterRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['registerApiAuthRegisterPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const registerApiAuthRegisterPost =  useRegisterApiAuthRegisterPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  registerApiAuthRegisterPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterApiAuthRegisterPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>>
    export type RegisterApiAuthRegisterPostMutationBody = RegisterRequest
    export type RegisterApiAuthRegisterPostMutationError = HTTPValidationError

    /**
 * @summary Register
 */
export const useRegisterApiAuthRegisterPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>, TError,{data: RegisterRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return useMutation(useRegisterApiAuthRegisterPostMutationOptions(options), queryClient);
    }
    /**
 * Login with email and password.
 * @summary Email Login
 */
export const useEmailLoginApiAuthEmailLoginPostHook = () => {
        const emailLoginApiAuthEmailLoginPost = useCustomInstance<TokenResponse>();

        return useCallback((
    emailLoginRequest: EmailLoginRequest,
 signal?: AbortSignal
) => {
        return emailLoginApiAuthEmailLoginPost(
          {url: `/api/auth/email-login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: emailLoginRequest, signal
    },
          );
        }, [emailLoginApiAuthEmailLoginPost])
      }



export const useEmailLoginApiAuthEmailLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useEmailLoginApiAuthEmailLoginPostHook>>>, TError,{data: EmailLoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useEmailLoginApiAuthEmailLoginPostHook>>>, TError,{data: EmailLoginRequest}, TContext> => {

const mutationKey = ['emailLoginApiAuthEmailLoginPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const emailLoginApiAuthEmailLoginPost =  useEmailLoginApiAuthEmailLoginPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useEmailLoginApiAuthEmailLoginPostHook>>>, {data: EmailLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  emailLoginApiAuthEmailLoginPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EmailLoginApiAuthEmailLoginPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useEmailLoginApiAuthEmailLoginPostHook>>>>
    export type EmailLoginApiAuthEmailLoginPostMutationBody = EmailLoginRequest
    export type EmailLoginApiAuthEmailLoginPostMutationError = HTTPValidationError

    /**
 * @summary Email Login
 */
export const useEmailLoginApiAuthEmailLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useEmailLoginApiAuthEmailLoginPostHook>>>, TError,{data: EmailLoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useEmailLoginApiAuthEmailLoginPostHook>>>,
        TError,
        {data: EmailLoginRequest},
        TContext
      > => {
      return useMutation(useEmailLoginApiAuthEmailLoginPostMutationOptions(options), queryClient);
    }
    /**
 * OAuth login endpoint.

Verify OAuth token, create/update user, and issue JWE tokens.
 * @summary Oauth Login
 */
export const useOauthLoginApiAuthLoginPostHook = () => {
        const oauthLoginApiAuthLoginPost = useCustomInstance<TokenResponse>();

        return useCallback((
    oAuthLoginRequest: OAuthLoginRequest,
 signal?: AbortSignal
) => {
        return oauthLoginApiAuthLoginPost(
          {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: oAuthLoginRequest, signal
    },
          );
        }, [oauthLoginApiAuthLoginPost])
      }



export const useOauthLoginApiAuthLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useOauthLoginApiAuthLoginPostHook>>>, TError,{data: OAuthLoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useOauthLoginApiAuthLoginPostHook>>>, TError,{data: OAuthLoginRequest}, TContext> => {

const mutationKey = ['oauthLoginApiAuthLoginPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const oauthLoginApiAuthLoginPost =  useOauthLoginApiAuthLoginPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useOauthLoginApiAuthLoginPostHook>>>, {data: OAuthLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  oauthLoginApiAuthLoginPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type OauthLoginApiAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useOauthLoginApiAuthLoginPostHook>>>>
    export type OauthLoginApiAuthLoginPostMutationBody = OAuthLoginRequest
    export type OauthLoginApiAuthLoginPostMutationError = HTTPValidationError

    /**
 * @summary Oauth Login
 */
export const useOauthLoginApiAuthLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useOauthLoginApiAuthLoginPostHook>>>, TError,{data: OAuthLoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useOauthLoginApiAuthLoginPostHook>>>,
        TError,
        {data: OAuthLoginRequest},
        TContext
      > => {
      return useMutation(useOauthLoginApiAuthLoginPostMutationOptions(options), queryClient);
    }
    /**
 * Refresh access token using refresh token.
 * @summary Refresh Token
 */
export const useRefreshTokenApiAuthRefreshPostHook = () => {
        const refreshTokenApiAuthRefreshPost = useCustomInstance<TokenResponse>();

        return useCallback((
    refreshTokenRequest: RefreshTokenRequest,
 signal?: AbortSignal
) => {
        return refreshTokenApiAuthRefreshPost(
          {url: `/api/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenRequest, signal
    },
          );
        }, [refreshTokenApiAuthRefreshPost])
      }



export const useRefreshTokenApiAuthRefreshPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, TError,{data: RefreshTokenRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, TError,{data: RefreshTokenRequest}, TContext> => {

const mutationKey = ['refreshTokenApiAuthRefreshPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const refreshTokenApiAuthRefreshPost =  useRefreshTokenApiAuthRefreshPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, {data: RefreshTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  refreshTokenApiAuthRefreshPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenApiAuthRefreshPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>>
    export type RefreshTokenApiAuthRefreshPostMutationBody = RefreshTokenRequest
    export type RefreshTokenApiAuthRefreshPostMutationError = HTTPValidationError

    /**
 * @summary Refresh Token
 */
export const useRefreshTokenApiAuthRefreshPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, TError,{data: RefreshTokenRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>,
        TError,
        {data: RefreshTokenRequest},
        TContext
      > => {
      return useMutation(useRefreshTokenApiAuthRefreshPostMutationOptions(options), queryClient);
    }
    /**
 * Logout endpoint.

Client should remove tokens from localStorage.
 * @summary Logout
 */
export const useLogoutApiAuthLogoutPostHook = () => {
        const logoutApiAuthLogoutPost = useCustomInstance<void>();

        return useCallback((

 signal?: AbortSignal
) => {
        return logoutApiAuthLogoutPost(
          {url: `/api/auth/logout`, method: 'POST', signal
    },
          );
        }, [logoutApiAuthLogoutPost])
      }



export const useLogoutApiAuthLogoutPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, TError,void, TContext> => {

const mutationKey = ['logoutApiAuthLogoutPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const logoutApiAuthLogoutPost =  useLogoutApiAuthLogoutPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, void> = () => {


          return  logoutApiAuthLogoutPost()
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutApiAuthLogoutPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>>

    export type LogoutApiAuthLogoutPostMutationError = unknown

    /**
 * @summary Logout
 */
export const useLogoutApiAuthLogoutPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(useLogoutApiAuthLogoutPostMutationOptions(options), queryClient);
    }
