/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  ArtifactListResponse,
  GenerateArtifactRequest,
  GeneratedArtifactResponse,
  HTTPValidationError,
  ListArtifactsEndpointApiLocalizerGetParams
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * Generate a learning artifact from saved resources via NotebookLM.
 * @summary Generate Artifact Endpoint
 */
export const useGenerateArtifactEndpointApiLocalizerGeneratePostHook = () => {
        const generateArtifactEndpointApiLocalizerGeneratePost = useCustomInstance<GeneratedArtifactResponse>();

        return useCallback((
    generateArtifactRequest: GenerateArtifactRequest,
 signal?: AbortSignal
) => {
        return generateArtifactEndpointApiLocalizerGeneratePost(
          {url: `/api/localizer/generate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: generateArtifactRequest, signal
    },
          );
        }, [generateArtifactEndpointApiLocalizerGeneratePost])
      }



export const useGenerateArtifactEndpointApiLocalizerGeneratePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useGenerateArtifactEndpointApiLocalizerGeneratePostHook>>>, TError,{data: GenerateArtifactRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useGenerateArtifactEndpointApiLocalizerGeneratePostHook>>>, TError,{data: GenerateArtifactRequest}, TContext> => {

const mutationKey = ['generateArtifactEndpointApiLocalizerGeneratePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const generateArtifactEndpointApiLocalizerGeneratePost =  useGenerateArtifactEndpointApiLocalizerGeneratePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useGenerateArtifactEndpointApiLocalizerGeneratePostHook>>>, {data: GenerateArtifactRequest}> = (props) => {
          const {data} = props ?? {};

          return  generateArtifactEndpointApiLocalizerGeneratePost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GenerateArtifactEndpointApiLocalizerGeneratePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGenerateArtifactEndpointApiLocalizerGeneratePostHook>>>>
    export type GenerateArtifactEndpointApiLocalizerGeneratePostMutationBody = GenerateArtifactRequest
    export type GenerateArtifactEndpointApiLocalizerGeneratePostMutationError = HTTPValidationError

    /**
 * @summary Generate Artifact Endpoint
 */
export const useGenerateArtifactEndpointApiLocalizerGeneratePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useGenerateArtifactEndpointApiLocalizerGeneratePostHook>>>, TError,{data: GenerateArtifactRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useGenerateArtifactEndpointApiLocalizerGeneratePostHook>>>,
        TError,
        {data: GenerateArtifactRequest},
        TContext
      > => {
      return useMutation(useGenerateArtifactEndpointApiLocalizerGeneratePostMutationOptions(options), queryClient);
    }
    /**
 * List generated artifacts for a preset.
 * @summary List Artifacts Endpoint
 */
export const useListArtifactsEndpointApiLocalizerGetHook = () => {
        const listArtifactsEndpointApiLocalizerGet = useCustomInstance<ArtifactListResponse>();

        return useCallback((
    params: ListArtifactsEndpointApiLocalizerGetParams,
 signal?: AbortSignal
) => {
        return listArtifactsEndpointApiLocalizerGet(
          {url: `/api/localizer`, method: 'GET',
        params, signal
    },
          );
        }, [listArtifactsEndpointApiLocalizerGet])
      }




export const getListArtifactsEndpointApiLocalizerGetInfiniteQueryKey = (params?: ListArtifactsEndpointApiLocalizerGetParams,) => {
    return [
    'infinite', `/api/localizer`, ...(params ? [params] : [])
    ] as const;
    }

export const getListArtifactsEndpointApiLocalizerGetQueryKey = (params?: ListArtifactsEndpointApiLocalizerGetParams,) => {
    return [
    `/api/localizer`, ...(params ? [params] : [])
    ] as const;
    }


export const useListArtifactsEndpointApiLocalizerGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>>, TError = HTTPValidationError>(params: ListArtifactsEndpointApiLocalizerGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListArtifactsEndpointApiLocalizerGetInfiniteQueryKey(params);

  const listArtifactsEndpointApiLocalizerGet =  useListArtifactsEndpointApiLocalizerGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>> = ({ signal }) => listArtifactsEndpointApiLocalizerGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListArtifactsEndpointApiLocalizerGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>>
export type ListArtifactsEndpointApiLocalizerGetInfiniteQueryError = HTTPValidationError


export function useListArtifactsEndpointApiLocalizerGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>>, TError = HTTPValidationError>(
 params: ListArtifactsEndpointApiLocalizerGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListArtifactsEndpointApiLocalizerGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>>, TError = HTTPValidationError>(
 params: ListArtifactsEndpointApiLocalizerGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListArtifactsEndpointApiLocalizerGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>>, TError = HTTPValidationError>(
 params: ListArtifactsEndpointApiLocalizerGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Artifacts Endpoint
 */

export function useListArtifactsEndpointApiLocalizerGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>>, TError = HTTPValidationError>(
 params: ListArtifactsEndpointApiLocalizerGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListArtifactsEndpointApiLocalizerGetInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListArtifactsEndpointApiLocalizerGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError = HTTPValidationError>(params: ListArtifactsEndpointApiLocalizerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListArtifactsEndpointApiLocalizerGetQueryKey(params);

  const listArtifactsEndpointApiLocalizerGet =  useListArtifactsEndpointApiLocalizerGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>> = ({ signal }) => listArtifactsEndpointApiLocalizerGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListArtifactsEndpointApiLocalizerGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>>
export type ListArtifactsEndpointApiLocalizerGetQueryError = HTTPValidationError


export function useListArtifactsEndpointApiLocalizerGet<TData = Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError = HTTPValidationError>(
 params: ListArtifactsEndpointApiLocalizerGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListArtifactsEndpointApiLocalizerGet<TData = Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError = HTTPValidationError>(
 params: ListArtifactsEndpointApiLocalizerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListArtifactsEndpointApiLocalizerGet<TData = Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError = HTTPValidationError>(
 params: ListArtifactsEndpointApiLocalizerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Artifacts Endpoint
 */

export function useListArtifactsEndpointApiLocalizerGet<TData = Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError = HTTPValidationError>(
 params: ListArtifactsEndpointApiLocalizerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListArtifactsEndpointApiLocalizerGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListArtifactsEndpointApiLocalizerGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError = HTTPValidationError>(params: ListArtifactsEndpointApiLocalizerGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListArtifactsEndpointApiLocalizerGetQueryKey(params);

  const listArtifactsEndpointApiLocalizerGet =  useListArtifactsEndpointApiLocalizerGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>> = ({ signal }) => listArtifactsEndpointApiLocalizerGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListArtifactsEndpointApiLocalizerGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>>
export type ListArtifactsEndpointApiLocalizerGetSuspenseQueryError = HTTPValidationError


export function useListArtifactsEndpointApiLocalizerGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError = HTTPValidationError>(
 params: ListArtifactsEndpointApiLocalizerGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListArtifactsEndpointApiLocalizerGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError = HTTPValidationError>(
 params: ListArtifactsEndpointApiLocalizerGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListArtifactsEndpointApiLocalizerGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError = HTTPValidationError>(
 params: ListArtifactsEndpointApiLocalizerGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Artifacts Endpoint
 */

export function useListArtifactsEndpointApiLocalizerGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError = HTTPValidationError>(
 params: ListArtifactsEndpointApiLocalizerGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListArtifactsEndpointApiLocalizerGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListArtifactsEndpointApiLocalizerGetSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get a single generated artifact.
 * @summary Get Artifact Endpoint
 */
export const useGetArtifactEndpointApiLocalizerArtifactIdGetHook = () => {
        const getArtifactEndpointApiLocalizerArtifactIdGet = useCustomInstance<GeneratedArtifactResponse>();

        return useCallback((
    artifactId: string,
 signal?: AbortSignal
) => {
        return getArtifactEndpointApiLocalizerArtifactIdGet(
          {url: `/api/localizer/${artifactId}`, method: 'GET', signal
    },
          );
        }, [getArtifactEndpointApiLocalizerArtifactIdGet])
      }




export const getGetArtifactEndpointApiLocalizerArtifactIdGetInfiniteQueryKey = (artifactId: string,) => {
    return [
    'infinite', `/api/localizer/${artifactId}`
    ] as const;
    }

export const getGetArtifactEndpointApiLocalizerArtifactIdGetQueryKey = (artifactId: string,) => {
    return [
    `/api/localizer/${artifactId}`
    ] as const;
    }


export const useGetArtifactEndpointApiLocalizerArtifactIdGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>>, TError = HTTPValidationError>(artifactId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetArtifactEndpointApiLocalizerArtifactIdGetInfiniteQueryKey(artifactId);

  const getArtifactEndpointApiLocalizerArtifactIdGet =  useGetArtifactEndpointApiLocalizerArtifactIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>> = ({ signal }) => getArtifactEndpointApiLocalizerArtifactIdGet(artifactId, signal);





   return  { queryKey, queryFn, enabled: !!(artifactId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetArtifactEndpointApiLocalizerArtifactIdGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>>
export type GetArtifactEndpointApiLocalizerArtifactIdGetInfiniteQueryError = HTTPValidationError


export function useGetArtifactEndpointApiLocalizerArtifactIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>>, TError = HTTPValidationError>(
 artifactId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArtifactEndpointApiLocalizerArtifactIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>>, TError = HTTPValidationError>(
 artifactId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArtifactEndpointApiLocalizerArtifactIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>>, TError = HTTPValidationError>(
 artifactId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Artifact Endpoint
 */

export function useGetArtifactEndpointApiLocalizerArtifactIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>>, TError = HTTPValidationError>(
 artifactId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetArtifactEndpointApiLocalizerArtifactIdGetInfiniteQueryOptions(artifactId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetArtifactEndpointApiLocalizerArtifactIdGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError = HTTPValidationError>(artifactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetArtifactEndpointApiLocalizerArtifactIdGetQueryKey(artifactId);

  const getArtifactEndpointApiLocalizerArtifactIdGet =  useGetArtifactEndpointApiLocalizerArtifactIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>> = ({ signal }) => getArtifactEndpointApiLocalizerArtifactIdGet(artifactId, signal);





   return  { queryKey, queryFn, enabled: !!(artifactId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetArtifactEndpointApiLocalizerArtifactIdGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>>
export type GetArtifactEndpointApiLocalizerArtifactIdGetQueryError = HTTPValidationError


export function useGetArtifactEndpointApiLocalizerArtifactIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError = HTTPValidationError>(
 artifactId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArtifactEndpointApiLocalizerArtifactIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError = HTTPValidationError>(
 artifactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArtifactEndpointApiLocalizerArtifactIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError = HTTPValidationError>(
 artifactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Artifact Endpoint
 */

export function useGetArtifactEndpointApiLocalizerArtifactIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError = HTTPValidationError>(
 artifactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetArtifactEndpointApiLocalizerArtifactIdGetQueryOptions(artifactId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetArtifactEndpointApiLocalizerArtifactIdGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError = HTTPValidationError>(artifactId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetArtifactEndpointApiLocalizerArtifactIdGetQueryKey(artifactId);

  const getArtifactEndpointApiLocalizerArtifactIdGet =  useGetArtifactEndpointApiLocalizerArtifactIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>> = ({ signal }) => getArtifactEndpointApiLocalizerArtifactIdGet(artifactId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetArtifactEndpointApiLocalizerArtifactIdGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>>
export type GetArtifactEndpointApiLocalizerArtifactIdGetSuspenseQueryError = HTTPValidationError


export function useGetArtifactEndpointApiLocalizerArtifactIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError = HTTPValidationError>(
 artifactId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArtifactEndpointApiLocalizerArtifactIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError = HTTPValidationError>(
 artifactId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArtifactEndpointApiLocalizerArtifactIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError = HTTPValidationError>(
 artifactId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Artifact Endpoint
 */

export function useGetArtifactEndpointApiLocalizerArtifactIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError = HTTPValidationError>(
 artifactId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetArtifactEndpointApiLocalizerArtifactIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetArtifactEndpointApiLocalizerArtifactIdGetSuspenseQueryOptions(artifactId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Delete a generated artifact.
 * @summary Delete Artifact Endpoint
 */
export const useDeleteArtifactEndpointApiLocalizerArtifactIdDeleteHook = () => {
        const deleteArtifactEndpointApiLocalizerArtifactIdDelete = useCustomInstance<void>();

        return useCallback((
    artifactId: string,
 signal?: AbortSignal
) => {
        return deleteArtifactEndpointApiLocalizerArtifactIdDelete(
          {url: `/api/localizer/${artifactId}`, method: 'DELETE', signal
    },
          );
        }, [deleteArtifactEndpointApiLocalizerArtifactIdDelete])
      }



export const useDeleteArtifactEndpointApiLocalizerArtifactIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteArtifactEndpointApiLocalizerArtifactIdDeleteHook>>>, TError,{artifactId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteArtifactEndpointApiLocalizerArtifactIdDeleteHook>>>, TError,{artifactId: string}, TContext> => {

const mutationKey = ['deleteArtifactEndpointApiLocalizerArtifactIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const deleteArtifactEndpointApiLocalizerArtifactIdDelete =  useDeleteArtifactEndpointApiLocalizerArtifactIdDeleteHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDeleteArtifactEndpointApiLocalizerArtifactIdDeleteHook>>>, {artifactId: string}> = (props) => {
          const {artifactId} = props ?? {};

          return  deleteArtifactEndpointApiLocalizerArtifactIdDelete(artifactId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteArtifactEndpointApiLocalizerArtifactIdDeleteMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDeleteArtifactEndpointApiLocalizerArtifactIdDeleteHook>>>>

    export type DeleteArtifactEndpointApiLocalizerArtifactIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Artifact Endpoint
 */
export const useDeleteArtifactEndpointApiLocalizerArtifactIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteArtifactEndpointApiLocalizerArtifactIdDeleteHook>>>, TError,{artifactId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDeleteArtifactEndpointApiLocalizerArtifactIdDeleteHook>>>,
        TError,
        {artifactId: string},
        TContext
      > => {
      return useMutation(useDeleteArtifactEndpointApiLocalizerArtifactIdDeleteMutationOptions(options), queryClient);
    }
