import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { type OklchColor, tokens } from "../src/tokens.js";
import { oklchToP3, p3ToFlutterColor } from "./oklch-to-p3.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, "../../../apps/mobile/lib/core/theme/generated_theme.dart");

function oklchToFlutter(oklch: OklchColor): string {
  const p3 = oklchToP3(oklch);
  return p3ToFlutterColor(p3);
}

// Infer keys from the light theme token definition
type TokenKey = keyof typeof tokens.color.light;

interface FColorSchemeMapping {
  property: string;
  tokenKey: TokenKey;
}

const colorSchemeMapping: FColorSchemeMapping[] = [
  { property: "barrier", tokenKey: "border" },
  { property: "background", tokenKey: "background" },
  { property: "foreground", tokenKey: "foreground" },
  { property: "primary", tokenKey: "primary" },
  { property: "primaryForeground", tokenKey: "primaryForeground" },
  { property: "secondary", tokenKey: "secondary" },
  { property: "secondaryForeground", tokenKey: "secondaryForeground" },
  { property: "muted", tokenKey: "muted" },
  { property: "mutedForeground", tokenKey: "mutedForeground" },
  { property: "destructive", tokenKey: "destructive" },
  { property: "destructiveForeground", tokenKey: "destructiveForeground" },
  { property: "error", tokenKey: "destructive" },
  { property: "errorForeground", tokenKey: "destructiveForeground" },
  { property: "border", tokenKey: "border" },
];

function generateColorProperties(colors: Record<string, OklchColor>): string {
  return colorSchemeMapping
    .map((mapping) => {
      const color = colors[mapping.tokenKey];
      const flutterColor = oklchToFlutter(color);
      return `    ${mapping.property}: ${flutterColor},`;
    })
    .join("\n");
}

function generateTheme(mode: "light" | "dark"): string {
  const colors = mode === "light" ? tokens.color.light : tokens.color.dark;
  const baseTheme = mode === "light" ? "FThemes.zinc.light" : "FThemes.zinc.dark";
  const themeName = mode === "light" ? "Light" : "Dark";

  return `final generated${themeName}Theme = ${baseTheme}.copyWith(
  colors: ${baseTheme}.colors.copyWith(
${generateColorProperties(colors)}
    hoverLighten: ${tokens.style.hoverLighten},
    hoverDarken: ${tokens.style.hoverDarken},
    disabledOpacity: ${tokens.style.disabledOpacity},
  ),
);`;
}

function generateDartFile(): string {
  return `// Generated by design-tokens package - DO NOT EDIT MANUALLY
// ignore_for_file: type=lint

import 'dart:ui' show Color, ColorSpace;

import 'package:forui/forui.dart';

${generateTheme("light")}

${generateTheme("dark")}
`;
}

function main(): void {
  console.log("🎨 Generating Flutter theme...");

  const dart = generateDartFile();

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, dart);

  console.log(`✅ Flutter theme written to: ${OUTPUT_PATH}`);
}

main();
