/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * List grouped saved resources in the library.
 * @summary List Saved Resources Endpoint
 */
export const ListSavedResourcesEndpointApiSavedGetQueryParams = zod.object({
  "preset_id": zod.union([zod.uuid(),zod.null()]).optional()
})

export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemResourceDataMetadataOneSourceDefault = `ddgs`;
export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemResourceDataMetadataTwoSourceDefault = `youtube`;
export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemResourceDataMetadataTwoDurationDefault = ``;
export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemResourceDataMetadataThreeSourceDefault = `openalex`;
export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemResourceDataMetadataFourSourceDefault = `custom`;
export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemEvaluationDataOneOverallScoreMin = 0;
export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemEvaluationDataOneOverallScoreMax = 10;

export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemEvaluationDataOneScoresScoreMax = 10;

export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemEvaluationDataOneScoresMaxDefault = 10;
export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemEvaluationDataOneAdversarialOneScoreAdjustmentsScoreMax = 10;

export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemEvaluationDataOneAdversarialOneScoreAdjustmentsMaxDefault = 10;

export const ListSavedResourcesEndpointApiSavedGetResponse = zod.object({
  "total": zod.number(),
  "groups": zod.array(zod.object({
  "preset_id": zod.uuid(),
  "preset_name": zod.string(),
  "preset_subject": zod.string(),
  "preset_topic": zod.union([zod.string(),zod.null()]).optional(),
  "query_groups": zod.array(zod.object({
  "search_query": zod.string(),
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource_url": zod.string(),
  "resource_data": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemResourceDataMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemResourceDataMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemResourceDataMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemResourceDataMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemResourceDataMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "evaluation_details": zod.union([zod.record(zod.string(), zod.record(zod.string(), zod.unknown())),zod.null()]).optional().describe('Detailed dimension scores')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "overall_score": zod.number().min(listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemEvaluationDataOneOverallScoreMin).max(listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemEvaluationDataOneOverallScoreMax),
  "relevance_reason": zod.string(),
  "recommended_use": zod.enum(['primary_resource', 'supplementary', 'reference_only']),
  "scores": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemEvaluationDataOneScoresScoreMax),
  "max": zod.number().default(listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemEvaluationDataOneScoresMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')),
  "adversarial": zod.union([zod.object({
  "verdict": zod.enum(['approved', 'approved_with_caveats', 'flagged_for_teacher_review', 'not_recommended']),
  "flags": zod.array(zod.object({
  "category": zod.enum(['false_positive', 'hidden_bias', 'accuracy_gap', 'safety', 'licensing_trap']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('Single issue raised by the adversarial reviewer.')).optional(),
  "score_adjustments": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemEvaluationDataOneAdversarialOneScoreAdjustmentsScoreMax),
  "max": zod.number().default(listSavedResourcesEndpointApiSavedGetResponseGroupsItemQueryGroupsItemItemsItemEvaluationDataOneAdversarialOneScoreAdjustmentsMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')).optional(),
  "review_summary": zod.string()
}).describe('Output of Agent 4 — challenges Agent 3 scores and surfaces risks.'),zod.null()]).optional()
}).describe('Full evaluation of a single resource across 7 dimensions.'),zod.null()]),
  "saved_at": zod.iso.datetime({})
}))
}).describe('A group of saved resources from the same search query.'))
}))
})

/**
 * Toggle save a resource from discovery defaults to idempotent insert.
 * @summary Toggle Save Resource Endpoint
 */
export const toggleSaveResourceEndpointApiSavedPostBodyResourceMetadataOneSourceDefault = `ddgs`;
export const toggleSaveResourceEndpointApiSavedPostBodyResourceMetadataTwoSourceDefault = `youtube`;
export const toggleSaveResourceEndpointApiSavedPostBodyResourceMetadataTwoDurationDefault = ``;
export const toggleSaveResourceEndpointApiSavedPostBodyResourceMetadataThreeSourceDefault = `openalex`;
export const toggleSaveResourceEndpointApiSavedPostBodyResourceMetadataFourSourceDefault = `custom`;
export const toggleSaveResourceEndpointApiSavedPostBodyEvaluationDataOneOverallScoreMin = 0;
export const toggleSaveResourceEndpointApiSavedPostBodyEvaluationDataOneOverallScoreMax = 10;

export const toggleSaveResourceEndpointApiSavedPostBodyEvaluationDataOneScoresScoreMax = 10;

export const toggleSaveResourceEndpointApiSavedPostBodyEvaluationDataOneScoresMaxDefault = 10;
export const toggleSaveResourceEndpointApiSavedPostBodyEvaluationDataOneAdversarialOneScoreAdjustmentsScoreMax = 10;

export const toggleSaveResourceEndpointApiSavedPostBodyEvaluationDataOneAdversarialOneScoreAdjustmentsMaxDefault = 10;

export const ToggleSaveResourceEndpointApiSavedPostBody = zod.object({
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(toggleSaveResourceEndpointApiSavedPostBodyResourceMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(toggleSaveResourceEndpointApiSavedPostBodyResourceMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(toggleSaveResourceEndpointApiSavedPostBodyResourceMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(toggleSaveResourceEndpointApiSavedPostBodyResourceMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(toggleSaveResourceEndpointApiSavedPostBodyResourceMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "evaluation_details": zod.union([zod.record(zod.string(), zod.record(zod.string(), zod.unknown())),zod.null()]).optional().describe('Detailed dimension scores')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "overall_score": zod.number().min(toggleSaveResourceEndpointApiSavedPostBodyEvaluationDataOneOverallScoreMin).max(toggleSaveResourceEndpointApiSavedPostBodyEvaluationDataOneOverallScoreMax),
  "relevance_reason": zod.string(),
  "recommended_use": zod.enum(['primary_resource', 'supplementary', 'reference_only']),
  "scores": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(toggleSaveResourceEndpointApiSavedPostBodyEvaluationDataOneScoresScoreMax),
  "max": zod.number().default(toggleSaveResourceEndpointApiSavedPostBodyEvaluationDataOneScoresMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')),
  "adversarial": zod.union([zod.object({
  "verdict": zod.enum(['approved', 'approved_with_caveats', 'flagged_for_teacher_review', 'not_recommended']),
  "flags": zod.array(zod.object({
  "category": zod.enum(['false_positive', 'hidden_bias', 'accuracy_gap', 'safety', 'licensing_trap']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('Single issue raised by the adversarial reviewer.')).optional(),
  "score_adjustments": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(toggleSaveResourceEndpointApiSavedPostBodyEvaluationDataOneAdversarialOneScoreAdjustmentsScoreMax),
  "max": zod.number().default(toggleSaveResourceEndpointApiSavedPostBodyEvaluationDataOneAdversarialOneScoreAdjustmentsMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')).optional(),
  "review_summary": zod.string()
}).describe('Output of Agent 4 — challenges Agent 3 scores and surfaces risks.'),zod.null()]).optional()
}).describe('Full evaluation of a single resource across 7 dimensions.'),zod.null()]).optional()
})

export const toggleSaveResourceEndpointApiSavedPostResponseResourceDataMetadataOneSourceDefault = `ddgs`;
export const toggleSaveResourceEndpointApiSavedPostResponseResourceDataMetadataTwoSourceDefault = `youtube`;
export const toggleSaveResourceEndpointApiSavedPostResponseResourceDataMetadataTwoDurationDefault = ``;
export const toggleSaveResourceEndpointApiSavedPostResponseResourceDataMetadataThreeSourceDefault = `openalex`;
export const toggleSaveResourceEndpointApiSavedPostResponseResourceDataMetadataFourSourceDefault = `custom`;
export const toggleSaveResourceEndpointApiSavedPostResponseEvaluationDataOneOverallScoreMin = 0;
export const toggleSaveResourceEndpointApiSavedPostResponseEvaluationDataOneOverallScoreMax = 10;

export const toggleSaveResourceEndpointApiSavedPostResponseEvaluationDataOneScoresScoreMax = 10;

export const toggleSaveResourceEndpointApiSavedPostResponseEvaluationDataOneScoresMaxDefault = 10;
export const toggleSaveResourceEndpointApiSavedPostResponseEvaluationDataOneAdversarialOneScoreAdjustmentsScoreMax = 10;

export const toggleSaveResourceEndpointApiSavedPostResponseEvaluationDataOneAdversarialOneScoreAdjustmentsMaxDefault = 10;

export const ToggleSaveResourceEndpointApiSavedPostResponse = zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource_url": zod.string(),
  "resource_data": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(toggleSaveResourceEndpointApiSavedPostResponseResourceDataMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(toggleSaveResourceEndpointApiSavedPostResponseResourceDataMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(toggleSaveResourceEndpointApiSavedPostResponseResourceDataMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(toggleSaveResourceEndpointApiSavedPostResponseResourceDataMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(toggleSaveResourceEndpointApiSavedPostResponseResourceDataMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "evaluation_details": zod.union([zod.record(zod.string(), zod.record(zod.string(), zod.unknown())),zod.null()]).optional().describe('Detailed dimension scores')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "overall_score": zod.number().min(toggleSaveResourceEndpointApiSavedPostResponseEvaluationDataOneOverallScoreMin).max(toggleSaveResourceEndpointApiSavedPostResponseEvaluationDataOneOverallScoreMax),
  "relevance_reason": zod.string(),
  "recommended_use": zod.enum(['primary_resource', 'supplementary', 'reference_only']),
  "scores": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(toggleSaveResourceEndpointApiSavedPostResponseEvaluationDataOneScoresScoreMax),
  "max": zod.number().default(toggleSaveResourceEndpointApiSavedPostResponseEvaluationDataOneScoresMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')),
  "adversarial": zod.union([zod.object({
  "verdict": zod.enum(['approved', 'approved_with_caveats', 'flagged_for_teacher_review', 'not_recommended']),
  "flags": zod.array(zod.object({
  "category": zod.enum(['false_positive', 'hidden_bias', 'accuracy_gap', 'safety', 'licensing_trap']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('Single issue raised by the adversarial reviewer.')).optional(),
  "score_adjustments": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(toggleSaveResourceEndpointApiSavedPostResponseEvaluationDataOneAdversarialOneScoreAdjustmentsScoreMax),
  "max": zod.number().default(toggleSaveResourceEndpointApiSavedPostResponseEvaluationDataOneAdversarialOneScoreAdjustmentsMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')).optional(),
  "review_summary": zod.string()
}).describe('Output of Agent 4 — challenges Agent 3 scores and surfaces risks.'),zod.null()]).optional()
}).describe('Full evaluation of a single resource across 7 dimensions.'),zod.null()]),
  "saved_at": zod.iso.datetime({})
})

/**
 * Save multiple resources in a single request.
 * @summary Bulk Save Resources Endpoint
 */
export const bulkSaveResourcesEndpointApiSavedBulkPostBodyResourcesItemMetadataOneSourceDefault = `ddgs`;
export const bulkSaveResourcesEndpointApiSavedBulkPostBodyResourcesItemMetadataTwoSourceDefault = `youtube`;
export const bulkSaveResourcesEndpointApiSavedBulkPostBodyResourcesItemMetadataTwoDurationDefault = ``;
export const bulkSaveResourcesEndpointApiSavedBulkPostBodyResourcesItemMetadataThreeSourceDefault = `openalex`;
export const bulkSaveResourcesEndpointApiSavedBulkPostBodyResourcesItemMetadataFourSourceDefault = `custom`;
export const bulkSaveResourcesEndpointApiSavedBulkPostBodyEvaluationDataListOneItemOneOverallScoreMin = 0;
export const bulkSaveResourcesEndpointApiSavedBulkPostBodyEvaluationDataListOneItemOneOverallScoreMax = 10;

export const bulkSaveResourcesEndpointApiSavedBulkPostBodyEvaluationDataListOneItemOneScoresScoreMax = 10;

export const bulkSaveResourcesEndpointApiSavedBulkPostBodyEvaluationDataListOneItemOneScoresMaxDefault = 10;
export const bulkSaveResourcesEndpointApiSavedBulkPostBodyEvaluationDataListOneItemOneAdversarialOneScoreAdjustmentsScoreMax = 10;

export const bulkSaveResourcesEndpointApiSavedBulkPostBodyEvaluationDataListOneItemOneAdversarialOneScoreAdjustmentsMaxDefault = 10;

export const BulkSaveResourcesEndpointApiSavedBulkPostBody = zod.object({
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resources": zod.array(zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(bulkSaveResourcesEndpointApiSavedBulkPostBodyResourcesItemMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(bulkSaveResourcesEndpointApiSavedBulkPostBodyResourcesItemMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(bulkSaveResourcesEndpointApiSavedBulkPostBodyResourcesItemMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(bulkSaveResourcesEndpointApiSavedBulkPostBodyResourcesItemMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(bulkSaveResourcesEndpointApiSavedBulkPostBodyResourcesItemMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "evaluation_details": zod.union([zod.record(zod.string(), zod.record(zod.string(), zod.unknown())),zod.null()]).optional().describe('Detailed dimension scores')
}).describe('Normalised resource card returned by all providers.')),
  "evaluation_data_list": zod.union([zod.array(zod.union([zod.object({
  "resource_url": zod.string(),
  "overall_score": zod.number().min(bulkSaveResourcesEndpointApiSavedBulkPostBodyEvaluationDataListOneItemOneOverallScoreMin).max(bulkSaveResourcesEndpointApiSavedBulkPostBodyEvaluationDataListOneItemOneOverallScoreMax),
  "relevance_reason": zod.string(),
  "recommended_use": zod.enum(['primary_resource', 'supplementary', 'reference_only']),
  "scores": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(bulkSaveResourcesEndpointApiSavedBulkPostBodyEvaluationDataListOneItemOneScoresScoreMax),
  "max": zod.number().default(bulkSaveResourcesEndpointApiSavedBulkPostBodyEvaluationDataListOneItemOneScoresMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')),
  "adversarial": zod.union([zod.object({
  "verdict": zod.enum(['approved', 'approved_with_caveats', 'flagged_for_teacher_review', 'not_recommended']),
  "flags": zod.array(zod.object({
  "category": zod.enum(['false_positive', 'hidden_bias', 'accuracy_gap', 'safety', 'licensing_trap']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('Single issue raised by the adversarial reviewer.')).optional(),
  "score_adjustments": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(bulkSaveResourcesEndpointApiSavedBulkPostBodyEvaluationDataListOneItemOneAdversarialOneScoreAdjustmentsScoreMax),
  "max": zod.number().default(bulkSaveResourcesEndpointApiSavedBulkPostBodyEvaluationDataListOneItemOneAdversarialOneScoreAdjustmentsMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')).optional(),
  "review_summary": zod.string()
}).describe('Output of Agent 4 — challenges Agent 3 scores and surfaces risks.'),zod.null()]).optional()
}).describe('Full evaluation of a single resource across 7 dimensions.'),zod.null()])),zod.null()]).optional()
})

export const bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemResourceDataMetadataOneSourceDefault = `ddgs`;
export const bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemResourceDataMetadataTwoSourceDefault = `youtube`;
export const bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemResourceDataMetadataTwoDurationDefault = ``;
export const bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemResourceDataMetadataThreeSourceDefault = `openalex`;
export const bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemResourceDataMetadataFourSourceDefault = `custom`;
export const bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemEvaluationDataOneOverallScoreMin = 0;
export const bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemEvaluationDataOneOverallScoreMax = 10;

export const bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemEvaluationDataOneScoresScoreMax = 10;

export const bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemEvaluationDataOneScoresMaxDefault = 10;
export const bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemEvaluationDataOneAdversarialOneScoreAdjustmentsScoreMax = 10;

export const bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemEvaluationDataOneAdversarialOneScoreAdjustmentsMaxDefault = 10;

export const BulkSaveResourcesEndpointApiSavedBulkPostResponse = zod.object({
  "saved": zod.array(zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource_url": zod.string(),
  "resource_data": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemResourceDataMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemResourceDataMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemResourceDataMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemResourceDataMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemResourceDataMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "evaluation_details": zod.union([zod.record(zod.string(), zod.record(zod.string(), zod.unknown())),zod.null()]).optional().describe('Detailed dimension scores')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "overall_score": zod.number().min(bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemEvaluationDataOneOverallScoreMin).max(bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemEvaluationDataOneOverallScoreMax),
  "relevance_reason": zod.string(),
  "recommended_use": zod.enum(['primary_resource', 'supplementary', 'reference_only']),
  "scores": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemEvaluationDataOneScoresScoreMax),
  "max": zod.number().default(bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemEvaluationDataOneScoresMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')),
  "adversarial": zod.union([zod.object({
  "verdict": zod.enum(['approved', 'approved_with_caveats', 'flagged_for_teacher_review', 'not_recommended']),
  "flags": zod.array(zod.object({
  "category": zod.enum(['false_positive', 'hidden_bias', 'accuracy_gap', 'safety', 'licensing_trap']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('Single issue raised by the adversarial reviewer.')).optional(),
  "score_adjustments": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemEvaluationDataOneAdversarialOneScoreAdjustmentsScoreMax),
  "max": zod.number().default(bulkSaveResourcesEndpointApiSavedBulkPostResponseSavedItemEvaluationDataOneAdversarialOneScoreAdjustmentsMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')).optional(),
  "review_summary": zod.string()
}).describe('Output of Agent 4 — challenges Agent 3 scores and surfaces risks.'),zod.null()]).optional()
}).describe('Full evaluation of a single resource across 7 dimensions.'),zod.null()]),
  "saved_at": zod.iso.datetime({})
})),
  "total": zod.number()
})

/**
 * Remove a saved resource from library.
 * @summary Delete Saved Resource Endpoint
 */
export const DeleteSavedResourceEndpointApiSavedIdDeleteParams = zod.object({
  "id": zod.uuid()
})

/**
 * Add and scrape a custom link.
 * @summary Add Custom Link Endpoint
 */
export const addCustomLinkEndpointApiSavedLinkPostBodyUrlMax = 2083;



export const AddCustomLinkEndpointApiSavedLinkPostBody = zod.object({
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "url": zod.url().min(1).max(addCustomLinkEndpointApiSavedLinkPostBodyUrlMax),
  "title": zod.union([zod.string(),zod.null()]).optional()
})

export const addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataOneSourceDefault = `ddgs`;
export const addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataTwoSourceDefault = `youtube`;
export const addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataTwoDurationDefault = ``;
export const addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataThreeSourceDefault = `openalex`;
export const addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataFourSourceDefault = `custom`;
export const addCustomLinkEndpointApiSavedLinkPostResponseEvaluationDataOneOverallScoreMin = 0;
export const addCustomLinkEndpointApiSavedLinkPostResponseEvaluationDataOneOverallScoreMax = 10;

export const addCustomLinkEndpointApiSavedLinkPostResponseEvaluationDataOneScoresScoreMax = 10;

export const addCustomLinkEndpointApiSavedLinkPostResponseEvaluationDataOneScoresMaxDefault = 10;
export const addCustomLinkEndpointApiSavedLinkPostResponseEvaluationDataOneAdversarialOneScoreAdjustmentsScoreMax = 10;

export const addCustomLinkEndpointApiSavedLinkPostResponseEvaluationDataOneAdversarialOneScoreAdjustmentsMaxDefault = 10;

export const AddCustomLinkEndpointApiSavedLinkPostResponse = zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource_url": zod.string(),
  "resource_data": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "evaluation_details": zod.union([zod.record(zod.string(), zod.record(zod.string(), zod.unknown())),zod.null()]).optional().describe('Detailed dimension scores')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "overall_score": zod.number().min(addCustomLinkEndpointApiSavedLinkPostResponseEvaluationDataOneOverallScoreMin).max(addCustomLinkEndpointApiSavedLinkPostResponseEvaluationDataOneOverallScoreMax),
  "relevance_reason": zod.string(),
  "recommended_use": zod.enum(['primary_resource', 'supplementary', 'reference_only']),
  "scores": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(addCustomLinkEndpointApiSavedLinkPostResponseEvaluationDataOneScoresScoreMax),
  "max": zod.number().default(addCustomLinkEndpointApiSavedLinkPostResponseEvaluationDataOneScoresMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')),
  "adversarial": zod.union([zod.object({
  "verdict": zod.enum(['approved', 'approved_with_caveats', 'flagged_for_teacher_review', 'not_recommended']),
  "flags": zod.array(zod.object({
  "category": zod.enum(['false_positive', 'hidden_bias', 'accuracy_gap', 'safety', 'licensing_trap']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('Single issue raised by the adversarial reviewer.')).optional(),
  "score_adjustments": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(addCustomLinkEndpointApiSavedLinkPostResponseEvaluationDataOneAdversarialOneScoreAdjustmentsScoreMax),
  "max": zod.number().default(addCustomLinkEndpointApiSavedLinkPostResponseEvaluationDataOneAdversarialOneScoreAdjustmentsMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')).optional(),
  "review_summary": zod.string()
}).describe('Output of Agent 4 — challenges Agent 3 scores and surfaces risks.'),zod.null()]).optional()
}).describe('Full evaluation of a single resource across 7 dimensions.'),zod.null()]),
  "saved_at": zod.iso.datetime({})
})

/**
 * Batch evaluate unevaluated library resources within a preset+query group.
 * @summary Evaluate Saved Resources Endpoint
 */
export const EvaluateSavedResourcesEndpointApiSavedEvaluatePostBody = zod.object({
  "preset_id": zod.uuid(),
  "search_query": zod.string()
})

export const EvaluateSavedResourcesEndpointApiSavedEvaluatePostResponse = zod.record(zod.string(), zod.unknown())

/**
 * Evaluate a single saved resource.
 * @summary Evaluate Single Resource Endpoint
 */
export const EvaluateSingleResourceEndpointApiSavedEvaluateSinglePostBody = zod.object({
  "saved_resource_id": zod.uuid()
})

export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataOneSourceDefault = `ddgs`;
export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataTwoSourceDefault = `youtube`;
export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataTwoDurationDefault = ``;
export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataThreeSourceDefault = `openalex`;
export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataFourSourceDefault = `custom`;
export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseEvaluationDataOneOverallScoreMin = 0;
export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseEvaluationDataOneOverallScoreMax = 10;

export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseEvaluationDataOneScoresScoreMax = 10;

export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseEvaluationDataOneScoresMaxDefault = 10;
export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseEvaluationDataOneAdversarialOneScoreAdjustmentsScoreMax = 10;

export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseEvaluationDataOneAdversarialOneScoreAdjustmentsMaxDefault = 10;

export const EvaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponse = zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource_url": zod.string(),
  "resource_data": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "evaluation_details": zod.union([zod.record(zod.string(), zod.record(zod.string(), zod.unknown())),zod.null()]).optional().describe('Detailed dimension scores')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "overall_score": zod.number().min(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseEvaluationDataOneOverallScoreMin).max(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseEvaluationDataOneOverallScoreMax),
  "relevance_reason": zod.string(),
  "recommended_use": zod.enum(['primary_resource', 'supplementary', 'reference_only']),
  "scores": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseEvaluationDataOneScoresScoreMax),
  "max": zod.number().default(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseEvaluationDataOneScoresMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')),
  "adversarial": zod.union([zod.object({
  "verdict": zod.enum(['approved', 'approved_with_caveats', 'flagged_for_teacher_review', 'not_recommended']),
  "flags": zod.array(zod.object({
  "category": zod.enum(['false_positive', 'hidden_bias', 'accuracy_gap', 'safety', 'licensing_trap']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('Single issue raised by the adversarial reviewer.')).optional(),
  "score_adjustments": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseEvaluationDataOneAdversarialOneScoreAdjustmentsScoreMax),
  "max": zod.number().default(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseEvaluationDataOneAdversarialOneScoreAdjustmentsMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.')).optional(),
  "review_summary": zod.string()
}).describe('Output of Agent 4 — challenges Agent 3 scores and surfaces risks.'),zod.null()]).optional()
}).describe('Full evaluation of a single resource across 7 dimensions.'),zod.null()]),
  "saved_at": zod.iso.datetime({})
})

