/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * List grouped saved resources in the library by collection.
 * @summary List Saved Resources Endpoint
 */
export const ListSavedResourcesEndpointApiSavedGetQueryParams = zod.object({
  "preset_id": zod.union([zod.uuid(),zod.null()]).optional()
})

export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemCollectionsItemItemsItemResourceDataMetadataOneSourceDefault = `ddgs`;
export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemCollectionsItemItemsItemResourceDataMetadataTwoSourceDefault = `youtube`;
export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemCollectionsItemItemsItemResourceDataMetadataTwoDurationDefault = ``;
export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemCollectionsItemItemsItemResourceDataMetadataThreeSourceDefault = `openalex`;
export const listSavedResourcesEndpointApiSavedGetResponseGroupsItemCollectionsItemItemsItemResourceDataMetadataFourSourceDefault = `custom`;

export const ListSavedResourcesEndpointApiSavedGetResponse = zod.object({
  "total": zod.number(),
  "groups": zod.array(zod.object({
  "preset_id": zod.uuid(),
  "preset_name": zod.string(),
  "preset_subject": zod.string(),
  "preset_topic": zod.union([zod.string(),zod.null()]).optional(),
  "collections": zod.array(zod.object({
  "collection": zod.object({
  "id": zod.uuid(),
  "user_id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "is_public": zod.boolean(),
  "clone_count": zod.number(),
  "created_at": zod.iso.datetime({})
}),
  "items": zod.array(zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource_url": zod.string(),
  "resource_data": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(listSavedResourcesEndpointApiSavedGetResponseGroupsItemCollectionsItemItemsItemResourceDataMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(listSavedResourcesEndpointApiSavedGetResponseGroupsItemCollectionsItemItemsItemResourceDataMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(listSavedResourcesEndpointApiSavedGetResponseGroupsItemCollectionsItemItemsItemResourceDataMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(listSavedResourcesEndpointApiSavedGetResponseGroupsItemCollectionsItemItemsItemResourceDataMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(listSavedResourcesEndpointApiSavedGetResponseGroupsItemCollectionsItemItemsItemResourceDataMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "verdict": zod.union([zod.string(),zod.null()]).optional().describe('use_it | adapt_it | skip_it')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "verdict": zod.enum(['use_it', 'adapt_it', 'skip_it']),
  "confidence": zod.enum(['high', 'moderate', 'low']),
  "curriculum_fit": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "accessibility": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "trustworthiness": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "reasoning_chain": zod.string(),
  "flags": zod.array(zod.object({
  "category": zod.enum(['outdated_content', 'bias_or_framing', 'factual_concern', 'safety_concern', 'misleading_match']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "evidence_quote": zod.string(),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('A single issue found by the risk scanner, backed by evidence.')).optional(),
  "adaptations": zod.array(zod.object({
  "action": zod.string(),
  "rationale": zod.string()
}).describe('A concrete adaptation the teacher can apply.')).optional(),
  "override_notes": zod.union([zod.string(),zod.null()]).optional()
}).describe('Final judgment combining triage + risk scan, presented to the teacher.'),zod.null()]).optional(),
  "evaluation_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "saved_at": zod.iso.datetime({})
}))
}).describe('A collection of saved resources.'))
}))
})

/**
 * Save a single resource, auto-creating a collection if needed.
 * @summary Save Resource Endpoint
 */
export const saveResourceEndpointApiSavedPostBodyResourceMetadataOneSourceDefault = `ddgs`;
export const saveResourceEndpointApiSavedPostBodyResourceMetadataTwoSourceDefault = `youtube`;
export const saveResourceEndpointApiSavedPostBodyResourceMetadataTwoDurationDefault = ``;
export const saveResourceEndpointApiSavedPostBodyResourceMetadataThreeSourceDefault = `openalex`;
export const saveResourceEndpointApiSavedPostBodyResourceMetadataFourSourceDefault = `custom`;

export const SaveResourceEndpointApiSavedPostBody = zod.object({
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(saveResourceEndpointApiSavedPostBodyResourceMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(saveResourceEndpointApiSavedPostBodyResourceMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(saveResourceEndpointApiSavedPostBodyResourceMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(saveResourceEndpointApiSavedPostBodyResourceMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(saveResourceEndpointApiSavedPostBodyResourceMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "verdict": zod.union([zod.string(),zod.null()]).optional().describe('use_it | adapt_it | skip_it')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "verdict": zod.enum(['use_it', 'adapt_it', 'skip_it']),
  "confidence": zod.enum(['high', 'moderate', 'low']),
  "curriculum_fit": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "accessibility": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "trustworthiness": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "reasoning_chain": zod.string(),
  "flags": zod.array(zod.object({
  "category": zod.enum(['outdated_content', 'bias_or_framing', 'factual_concern', 'safety_concern', 'misleading_match']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "evidence_quote": zod.string(),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('A single issue found by the risk scanner, backed by evidence.')).optional(),
  "adaptations": zod.array(zod.object({
  "action": zod.string(),
  "rationale": zod.string()
}).describe('A concrete adaptation the teacher can apply.')).optional(),
  "override_notes": zod.union([zod.string(),zod.null()]).optional()
}).describe('Final judgment combining triage + risk scan, presented to the teacher.'),zod.record(zod.string(), zod.unknown()),zod.null()]).optional()
})

export const saveResourceEndpointApiSavedPostResponseResourceDataMetadataOneSourceDefault = `ddgs`;
export const saveResourceEndpointApiSavedPostResponseResourceDataMetadataTwoSourceDefault = `youtube`;
export const saveResourceEndpointApiSavedPostResponseResourceDataMetadataTwoDurationDefault = ``;
export const saveResourceEndpointApiSavedPostResponseResourceDataMetadataThreeSourceDefault = `openalex`;
export const saveResourceEndpointApiSavedPostResponseResourceDataMetadataFourSourceDefault = `custom`;

export const SaveResourceEndpointApiSavedPostResponse = zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource_url": zod.string(),
  "resource_data": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(saveResourceEndpointApiSavedPostResponseResourceDataMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(saveResourceEndpointApiSavedPostResponseResourceDataMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(saveResourceEndpointApiSavedPostResponseResourceDataMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(saveResourceEndpointApiSavedPostResponseResourceDataMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(saveResourceEndpointApiSavedPostResponseResourceDataMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "verdict": zod.union([zod.string(),zod.null()]).optional().describe('use_it | adapt_it | skip_it')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "verdict": zod.enum(['use_it', 'adapt_it', 'skip_it']),
  "confidence": zod.enum(['high', 'moderate', 'low']),
  "curriculum_fit": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "accessibility": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "trustworthiness": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "reasoning_chain": zod.string(),
  "flags": zod.array(zod.object({
  "category": zod.enum(['outdated_content', 'bias_or_framing', 'factual_concern', 'safety_concern', 'misleading_match']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "evidence_quote": zod.string(),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('A single issue found by the risk scanner, backed by evidence.')).optional(),
  "adaptations": zod.array(zod.object({
  "action": zod.string(),
  "rationale": zod.string()
}).describe('A concrete adaptation the teacher can apply.')).optional(),
  "override_notes": zod.union([zod.string(),zod.null()]).optional()
}).describe('Final judgment combining triage + risk scan, presented to the teacher.'),zod.null()]).optional(),
  "evaluation_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "saved_at": zod.iso.datetime({})
})

/**
 * Get suggested public collections matching the search query via TF-IDF / FTS.
 * @summary Get Suggested Collections Endpoint
 */
export const getSuggestedCollectionsEndpointApiSavedSuggestedGetQueryLimitDefault = 5;

export const GetSuggestedCollectionsEndpointApiSavedSuggestedGetQueryParams = zod.object({
  "search_query": zod.string(),
  "preset_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "limit": zod.number().default(getSuggestedCollectionsEndpointApiSavedSuggestedGetQueryLimitDefault)
})

export const getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesCountDefault = 0;
export const getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseIsClonedByUserDefault = false;
export const getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseNeedsSyncDefault = false;
export const getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesItemResourceDataMetadataOneSourceDefault = `ddgs`;
export const getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesItemResourceDataMetadataTwoSourceDefault = `youtube`;
export const getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesItemResourceDataMetadataTwoDurationDefault = ``;
export const getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesItemResourceDataMetadataThreeSourceDefault = `openalex`;
export const getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesItemResourceDataMetadataFourSourceDefault = `custom`;
export const getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesDefault = [];

export const GetSuggestedCollectionsEndpointApiSavedSuggestedGetResponseItem = zod.object({
  "collection": zod.object({
  "id": zod.uuid(),
  "user_id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "is_public": zod.boolean(),
  "clone_count": zod.number(),
  "created_at": zod.iso.datetime({})
}),
  "matched_by": zod.string(),
  "resources_count": zod.number().default(getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesCountDefault),
  "publisher_name": zod.union([zod.string(),zod.null()]).optional(),
  "is_cloned_by_user": zod.boolean().default(getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseIsClonedByUserDefault),
  "needs_sync": zod.boolean().default(getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseNeedsSyncDefault),
  "resources": zod.array(zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource_url": zod.string(),
  "resource_data": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesItemResourceDataMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesItemResourceDataMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesItemResourceDataMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesItemResourceDataMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesItemResourceDataMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "verdict": zod.union([zod.string(),zod.null()]).optional().describe('use_it | adapt_it | skip_it')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "verdict": zod.enum(['use_it', 'adapt_it', 'skip_it']),
  "confidence": zod.enum(['high', 'moderate', 'low']),
  "curriculum_fit": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "accessibility": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "trustworthiness": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "reasoning_chain": zod.string(),
  "flags": zod.array(zod.object({
  "category": zod.enum(['outdated_content', 'bias_or_framing', 'factual_concern', 'safety_concern', 'misleading_match']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "evidence_quote": zod.string(),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('A single issue found by the risk scanner, backed by evidence.')).optional(),
  "adaptations": zod.array(zod.object({
  "action": zod.string(),
  "rationale": zod.string()
}).describe('A concrete adaptation the teacher can apply.')).optional(),
  "override_notes": zod.union([zod.string(),zod.null()]).optional()
}).describe('Final judgment combining triage + risk scan, presented to the teacher.'),zod.null()]).optional(),
  "evaluation_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "saved_at": zod.iso.datetime({})
})).default(getSuggestedCollectionsEndpointApiSavedSuggestedGetResponseResourcesDefault)
})
export const GetSuggestedCollectionsEndpointApiSavedSuggestedGetResponse = zod.array(GetSuggestedCollectionsEndpointApiSavedSuggestedGetResponseItem)

/**
 * Create a new collection from multiple resources.
 * @summary Create Collection Endpoint
 */
export const createCollectionEndpointApiSavedCollectionsPostBodyIsPublicDefault = false;
export const createCollectionEndpointApiSavedCollectionsPostBodyResourcesItemMetadataOneSourceDefault = `ddgs`;
export const createCollectionEndpointApiSavedCollectionsPostBodyResourcesItemMetadataTwoSourceDefault = `youtube`;
export const createCollectionEndpointApiSavedCollectionsPostBodyResourcesItemMetadataTwoDurationDefault = ``;
export const createCollectionEndpointApiSavedCollectionsPostBodyResourcesItemMetadataThreeSourceDefault = `openalex`;
export const createCollectionEndpointApiSavedCollectionsPostBodyResourcesItemMetadataFourSourceDefault = `custom`;

export const CreateCollectionEndpointApiSavedCollectionsPostBody = zod.object({
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "is_public": zod.boolean().default(createCollectionEndpointApiSavedCollectionsPostBodyIsPublicDefault),
  "resources": zod.array(zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(createCollectionEndpointApiSavedCollectionsPostBodyResourcesItemMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(createCollectionEndpointApiSavedCollectionsPostBodyResourcesItemMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(createCollectionEndpointApiSavedCollectionsPostBodyResourcesItemMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(createCollectionEndpointApiSavedCollectionsPostBodyResourcesItemMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(createCollectionEndpointApiSavedCollectionsPostBodyResourcesItemMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "verdict": zod.union([zod.string(),zod.null()]).optional().describe('use_it | adapt_it | skip_it')
}).describe('Normalised resource card returned by all providers.')),
  "evaluation_data_list": zod.union([zod.array(zod.union([zod.object({
  "resource_url": zod.string(),
  "verdict": zod.enum(['use_it', 'adapt_it', 'skip_it']),
  "confidence": zod.enum(['high', 'moderate', 'low']),
  "curriculum_fit": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "accessibility": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "trustworthiness": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "reasoning_chain": zod.string(),
  "flags": zod.array(zod.object({
  "category": zod.enum(['outdated_content', 'bias_or_framing', 'factual_concern', 'safety_concern', 'misleading_match']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "evidence_quote": zod.string(),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('A single issue found by the risk scanner, backed by evidence.')).optional(),
  "adaptations": zod.array(zod.object({
  "action": zod.string(),
  "rationale": zod.string()
}).describe('A concrete adaptation the teacher can apply.')).optional(),
  "override_notes": zod.union([zod.string(),zod.null()]).optional()
}).describe('Final judgment combining triage + risk scan, presented to the teacher.'),zod.null()])),zod.null()]).optional()
})

export const CreateCollectionEndpointApiSavedCollectionsPostResponse = zod.object({
  "id": zod.uuid(),
  "user_id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "is_public": zod.boolean(),
  "clone_count": zod.number(),
  "created_at": zod.iso.datetime({})
})

/**
 * Update a collection (e.g. rename, make public).
 * @summary Update Collection Endpoint
 */
export const UpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchParams = zod.object({
  "collection_id": zod.uuid()
})

export const UpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchBody = zod.object({
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "is_public": zod.union([zod.boolean(),zod.null()]).optional()
})

export const UpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchResponse = zod.object({
  "id": zod.uuid(),
  "user_id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "is_public": zod.boolean(),
  "clone_count": zod.number(),
  "created_at": zod.iso.datetime({})
})

/**
 * Delete a library collection permanently.
 * @summary Delete Collection Endpoint
 */
export const DeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteParams = zod.object({
  "collection_id": zod.uuid()
})

/**
 * Clone another user's public collection.
 * @summary Clone Collection Endpoint
 */
export const CloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostParams = zod.object({
  "collection_id": zod.uuid()
})

export const CloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostResponse = zod.object({
  "id": zod.uuid(),
  "user_id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "is_public": zod.boolean(),
  "clone_count": zod.number(),
  "created_at": zod.iso.datetime({})
})

/**
 * Sync a cloned collection with its original source.
 * @summary Sync Cloned Collection Endpoint
 */
export const SyncClonedCollectionEndpointApiSavedCollectionsCollectionIdSyncPostParams = zod.object({
  "collection_id": zod.uuid()
})

export const SyncClonedCollectionEndpointApiSavedCollectionsCollectionIdSyncPostResponse = zod.object({
  "id": zod.uuid(),
  "user_id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "is_public": zod.boolean(),
  "clone_count": zod.number(),
  "created_at": zod.iso.datetime({})
})

/**
 * Save a single resource to an existing collection.
 * @summary Save Resource To Collection Endpoint
 */
export const saveResourceToCollectionEndpointApiSavedCollectionItemPostBodyResourceMetadataOneSourceDefault = `ddgs`;
export const saveResourceToCollectionEndpointApiSavedCollectionItemPostBodyResourceMetadataTwoSourceDefault = `youtube`;
export const saveResourceToCollectionEndpointApiSavedCollectionItemPostBodyResourceMetadataTwoDurationDefault = ``;
export const saveResourceToCollectionEndpointApiSavedCollectionItemPostBodyResourceMetadataThreeSourceDefault = `openalex`;
export const saveResourceToCollectionEndpointApiSavedCollectionItemPostBodyResourceMetadataFourSourceDefault = `custom`;

export const SaveResourceToCollectionEndpointApiSavedCollectionItemPostBody = zod.object({
  "collection_id": zod.uuid(),
  "resource": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(saveResourceToCollectionEndpointApiSavedCollectionItemPostBodyResourceMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(saveResourceToCollectionEndpointApiSavedCollectionItemPostBodyResourceMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(saveResourceToCollectionEndpointApiSavedCollectionItemPostBodyResourceMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(saveResourceToCollectionEndpointApiSavedCollectionItemPostBodyResourceMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(saveResourceToCollectionEndpointApiSavedCollectionItemPostBodyResourceMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "verdict": zod.union([zod.string(),zod.null()]).optional().describe('use_it | adapt_it | skip_it')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "verdict": zod.enum(['use_it', 'adapt_it', 'skip_it']),
  "confidence": zod.enum(['high', 'moderate', 'low']),
  "curriculum_fit": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "accessibility": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "trustworthiness": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "reasoning_chain": zod.string(),
  "flags": zod.array(zod.object({
  "category": zod.enum(['outdated_content', 'bias_or_framing', 'factual_concern', 'safety_concern', 'misleading_match']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "evidence_quote": zod.string(),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('A single issue found by the risk scanner, backed by evidence.')).optional(),
  "adaptations": zod.array(zod.object({
  "action": zod.string(),
  "rationale": zod.string()
}).describe('A concrete adaptation the teacher can apply.')).optional(),
  "override_notes": zod.union([zod.string(),zod.null()]).optional()
}).describe('Final judgment combining triage + risk scan, presented to the teacher.'),zod.null()]).optional()
})

export const saveResourceToCollectionEndpointApiSavedCollectionItemPostResponseResourceDataMetadataOneSourceDefault = `ddgs`;
export const saveResourceToCollectionEndpointApiSavedCollectionItemPostResponseResourceDataMetadataTwoSourceDefault = `youtube`;
export const saveResourceToCollectionEndpointApiSavedCollectionItemPostResponseResourceDataMetadataTwoDurationDefault = ``;
export const saveResourceToCollectionEndpointApiSavedCollectionItemPostResponseResourceDataMetadataThreeSourceDefault = `openalex`;
export const saveResourceToCollectionEndpointApiSavedCollectionItemPostResponseResourceDataMetadataFourSourceDefault = `custom`;

export const SaveResourceToCollectionEndpointApiSavedCollectionItemPostResponse = zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource_url": zod.string(),
  "resource_data": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(saveResourceToCollectionEndpointApiSavedCollectionItemPostResponseResourceDataMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(saveResourceToCollectionEndpointApiSavedCollectionItemPostResponseResourceDataMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(saveResourceToCollectionEndpointApiSavedCollectionItemPostResponseResourceDataMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(saveResourceToCollectionEndpointApiSavedCollectionItemPostResponseResourceDataMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(saveResourceToCollectionEndpointApiSavedCollectionItemPostResponseResourceDataMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "verdict": zod.union([zod.string(),zod.null()]).optional().describe('use_it | adapt_it | skip_it')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "verdict": zod.enum(['use_it', 'adapt_it', 'skip_it']),
  "confidence": zod.enum(['high', 'moderate', 'low']),
  "curriculum_fit": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "accessibility": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "trustworthiness": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "reasoning_chain": zod.string(),
  "flags": zod.array(zod.object({
  "category": zod.enum(['outdated_content', 'bias_or_framing', 'factual_concern', 'safety_concern', 'misleading_match']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "evidence_quote": zod.string(),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('A single issue found by the risk scanner, backed by evidence.')).optional(),
  "adaptations": zod.array(zod.object({
  "action": zod.string(),
  "rationale": zod.string()
}).describe('A concrete adaptation the teacher can apply.')).optional(),
  "override_notes": zod.union([zod.string(),zod.null()]).optional()
}).describe('Final judgment combining triage + risk scan, presented to the teacher.'),zod.null()]).optional(),
  "evaluation_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "saved_at": zod.iso.datetime({})
})

/**
 * Remove a saved resource from library.
 * @summary Delete Saved Resource Endpoint
 */
export const DeleteSavedResourceEndpointApiSavedIdDeleteParams = zod.object({
  "id": zod.uuid()
})

/**
 * Add and scrape a custom link.
 * @summary Add Custom Link Endpoint
 */
export const addCustomLinkEndpointApiSavedLinkPostBodyUrlMax = 2083;



export const AddCustomLinkEndpointApiSavedLinkPostBody = zod.object({
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "url": zod.url().min(1).max(addCustomLinkEndpointApiSavedLinkPostBodyUrlMax),
  "title": zod.union([zod.string(),zod.null()]).optional()
})

export const addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataOneSourceDefault = `ddgs`;
export const addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataTwoSourceDefault = `youtube`;
export const addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataTwoDurationDefault = ``;
export const addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataThreeSourceDefault = `openalex`;
export const addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataFourSourceDefault = `custom`;

export const AddCustomLinkEndpointApiSavedLinkPostResponse = zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource_url": zod.string(),
  "resource_data": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(addCustomLinkEndpointApiSavedLinkPostResponseResourceDataMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "verdict": zod.union([zod.string(),zod.null()]).optional().describe('use_it | adapt_it | skip_it')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "verdict": zod.enum(['use_it', 'adapt_it', 'skip_it']),
  "confidence": zod.enum(['high', 'moderate', 'low']),
  "curriculum_fit": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "accessibility": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "trustworthiness": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "reasoning_chain": zod.string(),
  "flags": zod.array(zod.object({
  "category": zod.enum(['outdated_content', 'bias_or_framing', 'factual_concern', 'safety_concern', 'misleading_match']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "evidence_quote": zod.string(),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('A single issue found by the risk scanner, backed by evidence.')).optional(),
  "adaptations": zod.array(zod.object({
  "action": zod.string(),
  "rationale": zod.string()
}).describe('A concrete adaptation the teacher can apply.')).optional(),
  "override_notes": zod.union([zod.string(),zod.null()]).optional()
}).describe('Final judgment combining triage + risk scan, presented to the teacher.'),zod.null()]).optional(),
  "evaluation_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "saved_at": zod.iso.datetime({})
})

/**
 * Stream single resource evaluation progress as SSE events.
 * @summary Evaluate Single Stream Endpoint
 */
export const EvaluateSingleStreamEndpointApiSavedEvaluateSingleStreamGetQueryParams = zod.object({
  "saved_resource_id": zod.uuid()
})

export const EvaluateSingleStreamEndpointApiSavedEvaluateSingleStreamGetResponse = zod.unknown()

/**
 * Stream evaluation progress as SSE events.
 * @summary Evaluate Stream Endpoint
 */
export const EvaluateStreamEndpointApiSavedEvaluateStreamGetQueryParams = zod.object({
  "preset_id": zod.uuid(),
  "search_query": zod.string()
})

export const EvaluateStreamEndpointApiSavedEvaluateStreamGetResponse = zod.unknown()

/**
 * Batch evaluate unevaluated library resources within a preset+query group.
 * @summary Evaluate Saved Resources Endpoint
 */
export const EvaluateSavedResourcesEndpointApiSavedEvaluatePostBody = zod.object({
  "preset_id": zod.uuid(),
  "search_query": zod.string()
})

export const EvaluateSavedResourcesEndpointApiSavedEvaluatePostResponse = zod.record(zod.string(), zod.unknown())

/**
 * Evaluate a single saved resource.
 * @summary Evaluate Single Resource Endpoint
 */
export const EvaluateSingleResourceEndpointApiSavedEvaluateSinglePostBody = zod.object({
  "saved_resource_id": zod.uuid()
})

export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataOneSourceDefault = `ddgs`;
export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataTwoSourceDefault = `youtube`;
export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataTwoDurationDefault = ``;
export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataThreeSourceDefault = `openalex`;
export const evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataFourSourceDefault = `custom`;

export const EvaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponse = zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "search_query": zod.string(),
  "resource_url": zod.string(),
  "resource_data": zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex', 'custom']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "tags": zod.array(zod.string()).optional(),
  "full_description": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.'),zod.object({
  "source": zod.literal("custom").default(evaluateSingleResourceEndpointApiSavedEvaluateSinglePostResponseResourceDataMetadataFourSourceDefault),
  "domain": zod.string(),
  "og_title": zod.union([zod.string(),zod.null()]).optional(),
  "og_description": zod.union([zod.string(),zod.null()]).optional(),
  "og_image": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from manually added custom links.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "verdict": zod.union([zod.string(),zod.null()]).optional().describe('use_it | adapt_it | skip_it')
}).describe('Normalised resource card returned by all providers.'),
  "evaluation_data": zod.union([zod.object({
  "resource_url": zod.string(),
  "verdict": zod.enum(['use_it', 'adapt_it', 'skip_it']),
  "confidence": zod.enum(['high', 'moderate', 'low']),
  "curriculum_fit": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "accessibility": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "trustworthiness": zod.object({
  "rating": zod.enum(['strong', 'adequate', 'weak']),
  "reason": zod.string()
}).describe('One of the 3 evaluation metrics.'),
  "reasoning_chain": zod.string(),
  "flags": zod.array(zod.object({
  "category": zod.enum(['outdated_content', 'bias_or_framing', 'factual_concern', 'safety_concern', 'misleading_match']),
  "severity": zod.enum(['high', 'medium', 'low']),
  "evidence_quote": zod.string(),
  "explanation": zod.string(),
  "suggested_action": zod.string()
}).describe('A single issue found by the risk scanner, backed by evidence.')).optional(),
  "adaptations": zod.array(zod.object({
  "action": zod.string(),
  "rationale": zod.string()
}).describe('A concrete adaptation the teacher can apply.')).optional(),
  "override_notes": zod.union([zod.string(),zod.null()]).optional()
}).describe('Final judgment combining triage + risk scan, presented to the teacher.'),zod.null()]).optional(),
  "evaluation_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "saved_at": zod.iso.datetime({})
})

