/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Get Countries
 */
export const GetCountriesApiCurriculumCountriesGetResponseItem = zod.object({
  "code": zod.string(),
  "name": zod.string()
})
export const GetCountriesApiCurriculumCountriesGetResponse = zod.array(GetCountriesApiCurriculumCountriesGetResponseItem)

/**
 * @summary Get Subjects
 */
export const GetSubjectsApiCurriculumSubjectsGetQueryParams = zod.object({
  "country": zod.string()
})

export const GetSubjectsApiCurriculumSubjectsGetResponseItem = zod.string()
export const GetSubjectsApiCurriculumSubjectsGetResponse = zod.array(GetSubjectsApiCurriculumSubjectsGetResponseItem)

/**
 * @summary Get Frameworks
 */
export const GetFrameworksApiCurriculumFrameworksGetQueryParams = zod.object({
  "country": zod.string(),
  "subject": zod.string()
})

export const GetFrameworksApiCurriculumFrameworksGetResponseItem = zod.string()
export const GetFrameworksApiCurriculumFrameworksGetResponse = zod.array(GetFrameworksApiCurriculumFrameworksGetResponseItem)

/**
 * @summary Get Grades
 */
export const GetGradesApiCurriculumGradesGetQueryParams = zod.object({
  "country": zod.string(),
  "subject": zod.string(),
  "framework": zod.string()
})

export const GetGradesApiCurriculumGradesGetResponseItem = zod.object({
  "name": zod.string(),
  "sort_order": zod.number()
})
export const GetGradesApiCurriculumGradesGetResponse = zod.array(GetGradesApiCurriculumGradesGetResponseItem)

