/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Generate a learning artifact from saved resources via NotebookLM.
 * @summary Generate Artifact Endpoint
 */
export const generateArtifactEndpointApiLocalizerGeneratePostBodySavedResourceIdsMax = 10;



export const GenerateArtifactEndpointApiLocalizerGeneratePostBody = zod.object({
  "preset_id": zod.uuid(),
  "saved_resource_ids": zod.array(zod.uuid()).min(1).max(generateArtifactEndpointApiLocalizerGeneratePostBodySavedResourceIdsMax),
  "artifact_type": zod.enum(['quiz', 'mindmap', 'summary', 'flashcards'])
})

export const GenerateArtifactEndpointApiLocalizerGeneratePostResponse = zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "artifact_type": zod.string(),
  "content": zod.record(zod.string(), zod.unknown()),
  "source_resource_ids": zod.array(zod.uuid()),
  "created_at": zod.iso.datetime({})
})

/**
 * List generated artifacts for a preset.
 * @summary List Artifacts Endpoint
 */
export const ListArtifactsEndpointApiLocalizerGetQueryParams = zod.object({
  "preset_id": zod.uuid()
})

export const ListArtifactsEndpointApiLocalizerGetResponse = zod.object({
  "artifacts": zod.array(zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "artifact_type": zod.string(),
  "content": zod.record(zod.string(), zod.unknown()),
  "source_resource_ids": zod.array(zod.uuid()),
  "created_at": zod.iso.datetime({})
})),
  "total": zod.number()
})

/**
 * Get a single generated artifact.
 * @summary Get Artifact Endpoint
 */
export const GetArtifactEndpointApiLocalizerArtifactIdGetParams = zod.object({
  "artifact_id": zod.uuid()
})

export const GetArtifactEndpointApiLocalizerArtifactIdGetResponse = zod.object({
  "id": zod.uuid(),
  "preset_id": zod.uuid(),
  "artifact_type": zod.string(),
  "content": zod.record(zod.string(), zod.unknown()),
  "source_resource_ids": zod.array(zod.uuid()),
  "created_at": zod.iso.datetime({})
})

/**
 * Delete a generated artifact.
 * @summary Delete Artifact Endpoint
 */
export const DeleteArtifactEndpointApiLocalizerArtifactIdDeleteParams = zod.object({
  "artifact_id": zod.uuid()
})

