/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  HealthResponse,
  LivenessCheckHealthLiveGet200,
  ReadinessCheckHealthReadyGet200
} from '.././model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * Detailed health check endpoint with service statuses.
 * @summary Health Check
 */
export const useHealthCheckHealthGetHook = () => {
        const healthCheckHealthGet = useCustomInstance<HealthResponse>();

        return useCallback((
    
 signal?: AbortSignal
) => {
        return healthCheckHealthGet(
          {url: `/health`, method: 'GET', signal
    },
          );
        }, [healthCheckHealthGet])
      }
    



export const getHealthCheckHealthGetInfiniteQueryKey = () => {
    return [
    'infinite', `/health`
    ] as const;
    }

export const getHealthCheckHealthGetQueryKey = () => {
    return [
    `/health`
    ] as const;
    }

    
export const useHealthCheckHealthGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckHealthGetInfiniteQueryKey();

  const healthCheckHealthGet =  useHealthCheckHealthGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>> = ({ signal }) => healthCheckHealthGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthCheckHealthGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>>
export type HealthCheckHealthGetInfiniteQueryError = unknown


export function useHealthCheckHealthGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheckHealthGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheckHealthGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health Check
 */

export function useHealthCheckHealthGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useHealthCheckHealthGetInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useHealthCheckHealthGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckHealthGetQueryKey();

  const healthCheckHealthGet =  useHealthCheckHealthGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>> = ({ signal }) => healthCheckHealthGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthCheckHealthGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>>
export type HealthCheckHealthGetQueryError = unknown


export function useHealthCheckHealthGet<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheckHealthGet<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheckHealthGet<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health Check
 */

export function useHealthCheckHealthGet<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useHealthCheckHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useHealthCheckHealthGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckHealthGetQueryKey();

  const healthCheckHealthGet =  useHealthCheckHealthGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>> = ({ signal }) => healthCheckHealthGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthCheckHealthGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>>
export type HealthCheckHealthGetSuspenseQueryError = unknown


export function useHealthCheckHealthGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheckHealthGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheckHealthGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health Check
 */

export function useHealthCheckHealthGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useHealthCheckHealthGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useHealthCheckHealthGetSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Simple liveness probe for Kubernetes.
 * @summary Liveness Check
 */
export const useLivenessCheckHealthLiveGetHook = () => {
        const livenessCheckHealthLiveGet = useCustomInstance<LivenessCheckHealthLiveGet200>();

        return useCallback((
    
 signal?: AbortSignal
) => {
        return livenessCheckHealthLiveGet(
          {url: `/health/live`, method: 'GET', signal
    },
          );
        }, [livenessCheckHealthLiveGet])
      }
    



export const getLivenessCheckHealthLiveGetInfiniteQueryKey = () => {
    return [
    'infinite', `/health/live`
    ] as const;
    }

export const getLivenessCheckHealthLiveGetQueryKey = () => {
    return [
    `/health/live`
    ] as const;
    }

    
export const useLivenessCheckHealthLiveGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLivenessCheckHealthLiveGetInfiniteQueryKey();

  const livenessCheckHealthLiveGet =  useLivenessCheckHealthLiveGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>> = ({ signal }) => livenessCheckHealthLiveGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LivenessCheckHealthLiveGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>>
export type LivenessCheckHealthLiveGetInfiniteQueryError = unknown


export function useLivenessCheckHealthLiveGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLivenessCheckHealthLiveGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLivenessCheckHealthLiveGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Liveness Check
 */

export function useLivenessCheckHealthLiveGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useLivenessCheckHealthLiveGetInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useLivenessCheckHealthLiveGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLivenessCheckHealthLiveGetQueryKey();

  const livenessCheckHealthLiveGet =  useLivenessCheckHealthLiveGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>> = ({ signal }) => livenessCheckHealthLiveGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LivenessCheckHealthLiveGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>>
export type LivenessCheckHealthLiveGetQueryError = unknown


export function useLivenessCheckHealthLiveGet<TData = Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLivenessCheckHealthLiveGet<TData = Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLivenessCheckHealthLiveGet<TData = Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Liveness Check
 */

export function useLivenessCheckHealthLiveGet<TData = Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useLivenessCheckHealthLiveGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useLivenessCheckHealthLiveGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLivenessCheckHealthLiveGetQueryKey();

  const livenessCheckHealthLiveGet =  useLivenessCheckHealthLiveGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>> = ({ signal }) => livenessCheckHealthLiveGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LivenessCheckHealthLiveGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>>
export type LivenessCheckHealthLiveGetSuspenseQueryError = unknown


export function useLivenessCheckHealthLiveGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLivenessCheckHealthLiveGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLivenessCheckHealthLiveGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Liveness Check
 */

export function useLivenessCheckHealthLiveGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useLivenessCheckHealthLiveGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useLivenessCheckHealthLiveGetSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Readiness probe - checks if app can serve traffic.
 * @summary Readiness Check
 */
export const useReadinessCheckHealthReadyGetHook = () => {
        const readinessCheckHealthReadyGet = useCustomInstance<ReadinessCheckHealthReadyGet200>();

        return useCallback((
    
 signal?: AbortSignal
) => {
        return readinessCheckHealthReadyGet(
          {url: `/health/ready`, method: 'GET', signal
    },
          );
        }, [readinessCheckHealthReadyGet])
      }
    



export const getReadinessCheckHealthReadyGetInfiniteQueryKey = () => {
    return [
    'infinite', `/health/ready`
    ] as const;
    }

export const getReadinessCheckHealthReadyGetQueryKey = () => {
    return [
    `/health/ready`
    ] as const;
    }

    
export const useReadinessCheckHealthReadyGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadinessCheckHealthReadyGetInfiniteQueryKey();

  const readinessCheckHealthReadyGet =  useReadinessCheckHealthReadyGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>> = ({ signal }) => readinessCheckHealthReadyGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadinessCheckHealthReadyGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>>
export type ReadinessCheckHealthReadyGetInfiniteQueryError = unknown


export function useReadinessCheckHealthReadyGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadinessCheckHealthReadyGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadinessCheckHealthReadyGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Readiness Check
 */

export function useReadinessCheckHealthReadyGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useReadinessCheckHealthReadyGetInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useReadinessCheckHealthReadyGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadinessCheckHealthReadyGetQueryKey();

  const readinessCheckHealthReadyGet =  useReadinessCheckHealthReadyGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>> = ({ signal }) => readinessCheckHealthReadyGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadinessCheckHealthReadyGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>>
export type ReadinessCheckHealthReadyGetQueryError = unknown


export function useReadinessCheckHealthReadyGet<TData = Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadinessCheckHealthReadyGet<TData = Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadinessCheckHealthReadyGet<TData = Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Readiness Check
 */

export function useReadinessCheckHealthReadyGet<TData = Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useReadinessCheckHealthReadyGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useReadinessCheckHealthReadyGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadinessCheckHealthReadyGetQueryKey();

  const readinessCheckHealthReadyGet =  useReadinessCheckHealthReadyGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>> = ({ signal }) => readinessCheckHealthReadyGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadinessCheckHealthReadyGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>>
export type ReadinessCheckHealthReadyGetSuspenseQueryError = unknown


export function useReadinessCheckHealthReadyGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadinessCheckHealthReadyGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadinessCheckHealthReadyGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Readiness Check
 */

export function useReadinessCheckHealthReadyGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useReadinessCheckHealthReadyGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useReadinessCheckHealthReadyGetSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




