/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  GetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet200,
  HTTPValidationError,
  JudgedSearchResponse,
  SearchApiDiscoverySearchGetParams,
  SearchStreamApiDiscoverySearchStreamGetParams
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * Federated search across DuckDuckGo, YouTube, and OpenAlex.

Rate limited to 20 requests per minute per user.
Source labels: ddgs=DuckDuckGo, youtube=YouTube, openalex=OpenAlex
 * @summary Search
 */
export const useSearchApiDiscoverySearchGetHook = () => {
        const searchApiDiscoverySearchGet = useCustomInstance<JudgedSearchResponse>();

        return useCallback((
    params: SearchApiDiscoverySearchGetParams,
 signal?: AbortSignal
) => {
        return searchApiDiscoverySearchGet(
          {url: `/api/discovery/search`, method: 'GET',
        params, signal
    },
          );
        }, [searchApiDiscoverySearchGet])
      }




export const getSearchApiDiscoverySearchGetInfiniteQueryKey = (params?: SearchApiDiscoverySearchGetParams,) => {
    return [
    'infinite', `/api/discovery/search`, ...(params ? [params] : [])
    ] as const;
    }

export const getSearchApiDiscoverySearchGetQueryKey = (params?: SearchApiDiscoverySearchGetParams,) => {
    return [
    `/api/discovery/search`, ...(params ? [params] : [])
    ] as const;
    }


export const useSearchApiDiscoverySearchGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>>, TError = HTTPValidationError>(params: SearchApiDiscoverySearchGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchApiDiscoverySearchGetInfiniteQueryKey(params);

  const searchApiDiscoverySearchGet =  useSearchApiDiscoverySearchGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>> = ({ signal }) => searchApiDiscoverySearchGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchApiDiscoverySearchGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>>
export type SearchApiDiscoverySearchGetInfiniteQueryError = HTTPValidationError


export function useSearchApiDiscoverySearchGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>>, TError = HTTPValidationError>(
 params: SearchApiDiscoverySearchGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApiDiscoverySearchGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>>, TError = HTTPValidationError>(
 params: SearchApiDiscoverySearchGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApiDiscoverySearchGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>>, TError = HTTPValidationError>(
 params: SearchApiDiscoverySearchGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search
 */

export function useSearchApiDiscoverySearchGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>>, TError = HTTPValidationError>(
 params: SearchApiDiscoverySearchGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useSearchApiDiscoverySearchGetInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useSearchApiDiscoverySearchGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError = HTTPValidationError>(params: SearchApiDiscoverySearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchApiDiscoverySearchGetQueryKey(params);

  const searchApiDiscoverySearchGet =  useSearchApiDiscoverySearchGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>> = ({ signal }) => searchApiDiscoverySearchGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchApiDiscoverySearchGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>>
export type SearchApiDiscoverySearchGetQueryError = HTTPValidationError


export function useSearchApiDiscoverySearchGet<TData = Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError = HTTPValidationError>(
 params: SearchApiDiscoverySearchGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApiDiscoverySearchGet<TData = Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError = HTTPValidationError>(
 params: SearchApiDiscoverySearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApiDiscoverySearchGet<TData = Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError = HTTPValidationError>(
 params: SearchApiDiscoverySearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search
 */

export function useSearchApiDiscoverySearchGet<TData = Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError = HTTPValidationError>(
 params: SearchApiDiscoverySearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useSearchApiDiscoverySearchGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useSearchApiDiscoverySearchGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError = HTTPValidationError>(params: SearchApiDiscoverySearchGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchApiDiscoverySearchGetQueryKey(params);

  const searchApiDiscoverySearchGet =  useSearchApiDiscoverySearchGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>> = ({ signal }) => searchApiDiscoverySearchGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchApiDiscoverySearchGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>>
export type SearchApiDiscoverySearchGetSuspenseQueryError = HTTPValidationError


export function useSearchApiDiscoverySearchGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError = HTTPValidationError>(
 params: SearchApiDiscoverySearchGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApiDiscoverySearchGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError = HTTPValidationError>(
 params: SearchApiDiscoverySearchGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchApiDiscoverySearchGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError = HTTPValidationError>(
 params: SearchApiDiscoverySearchGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search
 */

export function useSearchApiDiscoverySearchGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError = HTTPValidationError>(
 params: SearchApiDiscoverySearchGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchApiDiscoverySearchGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useSearchApiDiscoverySearchGetSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * SSE stream of search pipeline progress.

Emits `SearchStageEvent` messages under the `stage` event name as the
multi-agent pipeline executes.  Rate limited to 20 requests per minute
per user.

The stream always terminates with a ``complete / done`` event whose
``data`` field contains the full ``JudgedSearchResponse``.
 * @summary Search Stream
 */
export const useSearchStreamApiDiscoverySearchStreamGetHook = () => {
        const searchStreamApiDiscoverySearchStreamGet = useCustomInstance<unknown>();

        return useCallback((
    params: SearchStreamApiDiscoverySearchStreamGetParams,
 signal?: AbortSignal
) => {
        return searchStreamApiDiscoverySearchStreamGet(
          {url: `/api/discovery/search/stream`, method: 'GET',
        params, signal
    },
          );
        }, [searchStreamApiDiscoverySearchStreamGet])
      }




export const getSearchStreamApiDiscoverySearchStreamGetInfiniteQueryKey = (params?: SearchStreamApiDiscoverySearchStreamGetParams,) => {
    return [
    'infinite', `/api/discovery/search/stream`, ...(params ? [params] : [])
    ] as const;
    }

export const getSearchStreamApiDiscoverySearchStreamGetQueryKey = (params?: SearchStreamApiDiscoverySearchStreamGetParams,) => {
    return [
    `/api/discovery/search/stream`, ...(params ? [params] : [])
    ] as const;
    }


export const useSearchStreamApiDiscoverySearchStreamGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>>, TError = HTTPValidationError>(params: SearchStreamApiDiscoverySearchStreamGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchStreamApiDiscoverySearchStreamGetInfiniteQueryKey(params);

  const searchStreamApiDiscoverySearchStreamGet =  useSearchStreamApiDiscoverySearchStreamGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>> = ({ signal }) => searchStreamApiDiscoverySearchStreamGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchStreamApiDiscoverySearchStreamGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>>
export type SearchStreamApiDiscoverySearchStreamGetInfiniteQueryError = HTTPValidationError


export function useSearchStreamApiDiscoverySearchStreamGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>>, TError = HTTPValidationError>(
 params: SearchStreamApiDiscoverySearchStreamGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchStreamApiDiscoverySearchStreamGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>>, TError = HTTPValidationError>(
 params: SearchStreamApiDiscoverySearchStreamGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchStreamApiDiscoverySearchStreamGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>>, TError = HTTPValidationError>(
 params: SearchStreamApiDiscoverySearchStreamGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search Stream
 */

export function useSearchStreamApiDiscoverySearchStreamGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>>, TError = HTTPValidationError>(
 params: SearchStreamApiDiscoverySearchStreamGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useSearchStreamApiDiscoverySearchStreamGetInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useSearchStreamApiDiscoverySearchStreamGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError = HTTPValidationError>(params: SearchStreamApiDiscoverySearchStreamGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchStreamApiDiscoverySearchStreamGetQueryKey(params);

  const searchStreamApiDiscoverySearchStreamGet =  useSearchStreamApiDiscoverySearchStreamGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>> = ({ signal }) => searchStreamApiDiscoverySearchStreamGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchStreamApiDiscoverySearchStreamGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>>
export type SearchStreamApiDiscoverySearchStreamGetQueryError = HTTPValidationError


export function useSearchStreamApiDiscoverySearchStreamGet<TData = Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError = HTTPValidationError>(
 params: SearchStreamApiDiscoverySearchStreamGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchStreamApiDiscoverySearchStreamGet<TData = Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError = HTTPValidationError>(
 params: SearchStreamApiDiscoverySearchStreamGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchStreamApiDiscoverySearchStreamGet<TData = Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError = HTTPValidationError>(
 params: SearchStreamApiDiscoverySearchStreamGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search Stream
 */

export function useSearchStreamApiDiscoverySearchStreamGet<TData = Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError = HTTPValidationError>(
 params: SearchStreamApiDiscoverySearchStreamGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useSearchStreamApiDiscoverySearchStreamGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useSearchStreamApiDiscoverySearchStreamGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError = HTTPValidationError>(params: SearchStreamApiDiscoverySearchStreamGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchStreamApiDiscoverySearchStreamGetQueryKey(params);

  const searchStreamApiDiscoverySearchStreamGet =  useSearchStreamApiDiscoverySearchStreamGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>> = ({ signal }) => searchStreamApiDiscoverySearchStreamGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchStreamApiDiscoverySearchStreamGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>>
export type SearchStreamApiDiscoverySearchStreamGetSuspenseQueryError = HTTPValidationError


export function useSearchStreamApiDiscoverySearchStreamGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError = HTTPValidationError>(
 params: SearchStreamApiDiscoverySearchStreamGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchStreamApiDiscoverySearchStreamGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError = HTTPValidationError>(
 params: SearchStreamApiDiscoverySearchStreamGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchStreamApiDiscoverySearchStreamGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError = HTTPValidationError>(
 params: SearchStreamApiDiscoverySearchStreamGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search Stream
 */

export function useSearchStreamApiDiscoverySearchStreamGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError = HTTPValidationError>(
 params: SearchStreamApiDiscoverySearchStreamGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchStreamApiDiscoverySearchStreamGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useSearchStreamApiDiscoverySearchStreamGetSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Fetch evaluation data by ID.
 * @summary Get Evaluation Endpoint
 */
export const useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook = () => {
        const getEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet = useCustomInstance<GetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet200>();

        return useCallback((
    evaluationId: string,
 signal?: AbortSignal
) => {
        return getEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet(
          {url: `/api/discovery/evaluation/${evaluationId}`, method: 'GET', signal
    },
          );
        }, [getEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet])
      }




export const getGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetInfiniteQueryKey = (evaluationId: string,) => {
    return [
    'infinite', `/api/discovery/evaluation/${evaluationId}`
    ] as const;
    }

export const getGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetQueryKey = (evaluationId: string,) => {
    return [
    `/api/discovery/evaluation/${evaluationId}`
    ] as const;
    }


export const useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>>, TError = HTTPValidationError>(evaluationId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetInfiniteQueryKey(evaluationId);

  const getEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet =  useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>> = ({ signal }) => getEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet(evaluationId, signal);





   return  { queryKey, queryFn, enabled: !!(evaluationId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>>
export type GetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetInfiniteQueryError = HTTPValidationError


export function useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>>, TError = HTTPValidationError>(
 evaluationId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>>, TError = HTTPValidationError>(
 evaluationId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>>, TError = HTTPValidationError>(
 evaluationId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Evaluation Endpoint
 */

export function useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>>, TError = HTTPValidationError>(
 evaluationId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetInfiniteQueryOptions(evaluationId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError = HTTPValidationError>(evaluationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetQueryKey(evaluationId);

  const getEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet =  useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>> = ({ signal }) => getEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet(evaluationId, signal);





   return  { queryKey, queryFn, enabled: !!(evaluationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>>
export type GetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetQueryError = HTTPValidationError


export function useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError = HTTPValidationError>(
 evaluationId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError = HTTPValidationError>(
 evaluationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError = HTTPValidationError>(
 evaluationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Evaluation Endpoint
 */

export function useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError = HTTPValidationError>(
 evaluationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetQueryOptions(evaluationId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError = HTTPValidationError>(evaluationId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetQueryKey(evaluationId);

  const getEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet =  useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>> = ({ signal }) => getEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGet(evaluationId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>>
export type GetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetSuspenseQueryError = HTTPValidationError


export function useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError = HTTPValidationError>(
 evaluationId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError = HTTPValidationError>(
 evaluationId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError = HTTPValidationError>(
 evaluationId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Evaluation Endpoint
 */

export function useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError = HTTPValidationError>(
 evaluationId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetEvaluationEndpointApiDiscoveryEvaluationEvaluationIdGetSuspenseQueryOptions(evaluationId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




