/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  AddCustomLinkRequest,
  BatchEvaluateRequest,
  EvaluateSavedResourcesEndpointApiSavedEvaluatePost200,
  EvaluateSingleRequest,
  GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams,
  HTTPValidationError,
  LibraryCollectionCreate,
  LibraryCollectionResponse,
  LibraryCollectionUpdate,
  ListSavedResourcesEndpointApiSavedGetParams,
  SaveResourceRequest,
  SaveResourceToCollectionRequest,
  SavedResourceListResponse,
  SavedResourceResponse,
  SuggestedCollectionResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * List grouped saved resources in the library by collection.
 * @summary List Saved Resources Endpoint
 */
export const useListSavedResourcesEndpointApiSavedGetHook = () => {
        const listSavedResourcesEndpointApiSavedGet = useCustomInstance<SavedResourceListResponse>();

        return useCallback((
    params?: ListSavedResourcesEndpointApiSavedGetParams,
 signal?: AbortSignal
) => {
        return listSavedResourcesEndpointApiSavedGet(
          {url: `/api/saved`, method: 'GET',
        params, signal
    },
          );
        }, [listSavedResourcesEndpointApiSavedGet])
      }




export const getListSavedResourcesEndpointApiSavedGetInfiniteQueryKey = (params?: ListSavedResourcesEndpointApiSavedGetParams,) => {
    return [
    'infinite', `/api/saved`, ...(params ? [params] : [])
    ] as const;
    }

export const getListSavedResourcesEndpointApiSavedGetQueryKey = (params?: ListSavedResourcesEndpointApiSavedGetParams,) => {
    return [
    `/api/saved`, ...(params ? [params] : [])
    ] as const;
    }


export const useListSavedResourcesEndpointApiSavedGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>>, TError = HTTPValidationError>(params?: ListSavedResourcesEndpointApiSavedGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSavedResourcesEndpointApiSavedGetInfiniteQueryKey(params);

  const listSavedResourcesEndpointApiSavedGet =  useListSavedResourcesEndpointApiSavedGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>> = ({ signal }) => listSavedResourcesEndpointApiSavedGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSavedResourcesEndpointApiSavedGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>>
export type ListSavedResourcesEndpointApiSavedGetInfiniteQueryError = HTTPValidationError


export function useListSavedResourcesEndpointApiSavedGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>>, TError = HTTPValidationError>(
 params: undefined |  ListSavedResourcesEndpointApiSavedGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSavedResourcesEndpointApiSavedGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>>, TError = HTTPValidationError>(
 params?: ListSavedResourcesEndpointApiSavedGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSavedResourcesEndpointApiSavedGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>>, TError = HTTPValidationError>(
 params?: ListSavedResourcesEndpointApiSavedGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Saved Resources Endpoint
 */

export function useListSavedResourcesEndpointApiSavedGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>>, TError = HTTPValidationError>(
 params?: ListSavedResourcesEndpointApiSavedGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListSavedResourcesEndpointApiSavedGetInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListSavedResourcesEndpointApiSavedGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError = HTTPValidationError>(params?: ListSavedResourcesEndpointApiSavedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSavedResourcesEndpointApiSavedGetQueryKey(params);

  const listSavedResourcesEndpointApiSavedGet =  useListSavedResourcesEndpointApiSavedGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>> = ({ signal }) => listSavedResourcesEndpointApiSavedGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSavedResourcesEndpointApiSavedGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>>
export type ListSavedResourcesEndpointApiSavedGetQueryError = HTTPValidationError


export function useListSavedResourcesEndpointApiSavedGet<TData = Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError = HTTPValidationError>(
 params: undefined |  ListSavedResourcesEndpointApiSavedGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSavedResourcesEndpointApiSavedGet<TData = Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError = HTTPValidationError>(
 params?: ListSavedResourcesEndpointApiSavedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSavedResourcesEndpointApiSavedGet<TData = Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError = HTTPValidationError>(
 params?: ListSavedResourcesEndpointApiSavedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Saved Resources Endpoint
 */

export function useListSavedResourcesEndpointApiSavedGet<TData = Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError = HTTPValidationError>(
 params?: ListSavedResourcesEndpointApiSavedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListSavedResourcesEndpointApiSavedGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListSavedResourcesEndpointApiSavedGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError = HTTPValidationError>(params?: ListSavedResourcesEndpointApiSavedGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSavedResourcesEndpointApiSavedGetQueryKey(params);

  const listSavedResourcesEndpointApiSavedGet =  useListSavedResourcesEndpointApiSavedGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>> = ({ signal }) => listSavedResourcesEndpointApiSavedGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSavedResourcesEndpointApiSavedGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>>
export type ListSavedResourcesEndpointApiSavedGetSuspenseQueryError = HTTPValidationError


export function useListSavedResourcesEndpointApiSavedGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError = HTTPValidationError>(
 params: undefined |  ListSavedResourcesEndpointApiSavedGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSavedResourcesEndpointApiSavedGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError = HTTPValidationError>(
 params?: ListSavedResourcesEndpointApiSavedGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSavedResourcesEndpointApiSavedGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError = HTTPValidationError>(
 params?: ListSavedResourcesEndpointApiSavedGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Saved Resources Endpoint
 */

export function useListSavedResourcesEndpointApiSavedGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError = HTTPValidationError>(
 params?: ListSavedResourcesEndpointApiSavedGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSavedResourcesEndpointApiSavedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListSavedResourcesEndpointApiSavedGetSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Save a single resource, auto-creating a collection if needed.
 * @summary Save Resource Endpoint
 */
export const useSaveResourceEndpointApiSavedPostHook = () => {
        const saveResourceEndpointApiSavedPost = useCustomInstance<SavedResourceResponse>();

        return useCallback((
    saveResourceRequest: SaveResourceRequest,
 signal?: AbortSignal
) => {
        return saveResourceEndpointApiSavedPost(
          {url: `/api/saved`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: saveResourceRequest, signal
    },
          );
        }, [saveResourceEndpointApiSavedPost])
      }



export const useSaveResourceEndpointApiSavedPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSaveResourceEndpointApiSavedPostHook>>>, TError,{data: SaveResourceRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSaveResourceEndpointApiSavedPostHook>>>, TError,{data: SaveResourceRequest}, TContext> => {

const mutationKey = ['saveResourceEndpointApiSavedPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const saveResourceEndpointApiSavedPost =  useSaveResourceEndpointApiSavedPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useSaveResourceEndpointApiSavedPostHook>>>, {data: SaveResourceRequest}> = (props) => {
          const {data} = props ?? {};

          return  saveResourceEndpointApiSavedPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaveResourceEndpointApiSavedPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSaveResourceEndpointApiSavedPostHook>>>>
    export type SaveResourceEndpointApiSavedPostMutationBody = SaveResourceRequest
    export type SaveResourceEndpointApiSavedPostMutationError = HTTPValidationError

    /**
 * @summary Save Resource Endpoint
 */
export const useSaveResourceEndpointApiSavedPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSaveResourceEndpointApiSavedPostHook>>>, TError,{data: SaveResourceRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useSaveResourceEndpointApiSavedPostHook>>>,
        TError,
        {data: SaveResourceRequest},
        TContext
      > => {
      return useMutation(useSaveResourceEndpointApiSavedPostMutationOptions(options), queryClient);
    }
    /**
 * Get suggested public collections matching the search query via TF-IDF / FTS.
 * @summary Get Suggested Collections Endpoint
 */
export const useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook = () => {
        const getSuggestedCollectionsEndpointApiSavedSuggestedGet = useCustomInstance<SuggestedCollectionResponse[]>();

        return useCallback((
    params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams,
 signal?: AbortSignal
) => {
        return getSuggestedCollectionsEndpointApiSavedSuggestedGet(
          {url: `/api/saved/suggested`, method: 'GET',
        params, signal
    },
          );
        }, [getSuggestedCollectionsEndpointApiSavedSuggestedGet])
      }




export const getGetSuggestedCollectionsEndpointApiSavedSuggestedGetInfiniteQueryKey = (params?: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams,) => {
    return [
    'infinite', `/api/saved/suggested`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetSuggestedCollectionsEndpointApiSavedSuggestedGetQueryKey = (params?: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams,) => {
    return [
    `/api/saved/suggested`, ...(params ? [params] : [])
    ] as const;
    }


export const useGetSuggestedCollectionsEndpointApiSavedSuggestedGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>>, TError = HTTPValidationError>(params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSuggestedCollectionsEndpointApiSavedSuggestedGetInfiniteQueryKey(params);

  const getSuggestedCollectionsEndpointApiSavedSuggestedGet =  useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>> = ({ signal }) => getSuggestedCollectionsEndpointApiSavedSuggestedGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSuggestedCollectionsEndpointApiSavedSuggestedGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>>
export type GetSuggestedCollectionsEndpointApiSavedSuggestedGetInfiniteQueryError = HTTPValidationError


export function useGetSuggestedCollectionsEndpointApiSavedSuggestedGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>>, TError = HTTPValidationError>(
 params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSuggestedCollectionsEndpointApiSavedSuggestedGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>>, TError = HTTPValidationError>(
 params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSuggestedCollectionsEndpointApiSavedSuggestedGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>>, TError = HTTPValidationError>(
 params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Suggested Collections Endpoint
 */

export function useGetSuggestedCollectionsEndpointApiSavedSuggestedGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>>, TError = HTTPValidationError>(
 params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetSuggestedCollectionsEndpointApiSavedSuggestedGetInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetSuggestedCollectionsEndpointApiSavedSuggestedGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError = HTTPValidationError>(params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSuggestedCollectionsEndpointApiSavedSuggestedGetQueryKey(params);

  const getSuggestedCollectionsEndpointApiSavedSuggestedGet =  useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>> = ({ signal }) => getSuggestedCollectionsEndpointApiSavedSuggestedGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSuggestedCollectionsEndpointApiSavedSuggestedGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>>
export type GetSuggestedCollectionsEndpointApiSavedSuggestedGetQueryError = HTTPValidationError


export function useGetSuggestedCollectionsEndpointApiSavedSuggestedGet<TData = Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError = HTTPValidationError>(
 params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSuggestedCollectionsEndpointApiSavedSuggestedGet<TData = Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError = HTTPValidationError>(
 params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSuggestedCollectionsEndpointApiSavedSuggestedGet<TData = Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError = HTTPValidationError>(
 params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Suggested Collections Endpoint
 */

export function useGetSuggestedCollectionsEndpointApiSavedSuggestedGet<TData = Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError = HTTPValidationError>(
 params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetSuggestedCollectionsEndpointApiSavedSuggestedGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetSuggestedCollectionsEndpointApiSavedSuggestedGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError = HTTPValidationError>(params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSuggestedCollectionsEndpointApiSavedSuggestedGetQueryKey(params);

  const getSuggestedCollectionsEndpointApiSavedSuggestedGet =  useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>> = ({ signal }) => getSuggestedCollectionsEndpointApiSavedSuggestedGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSuggestedCollectionsEndpointApiSavedSuggestedGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>>
export type GetSuggestedCollectionsEndpointApiSavedSuggestedGetSuspenseQueryError = HTTPValidationError


export function useGetSuggestedCollectionsEndpointApiSavedSuggestedGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError = HTTPValidationError>(
 params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSuggestedCollectionsEndpointApiSavedSuggestedGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError = HTTPValidationError>(
 params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSuggestedCollectionsEndpointApiSavedSuggestedGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError = HTTPValidationError>(
 params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Suggested Collections Endpoint
 */

export function useGetSuggestedCollectionsEndpointApiSavedSuggestedGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError = HTTPValidationError>(
 params: GetSuggestedCollectionsEndpointApiSavedSuggestedGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSuggestedCollectionsEndpointApiSavedSuggestedGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetSuggestedCollectionsEndpointApiSavedSuggestedGetSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new collection from multiple resources.
 * @summary Create Collection Endpoint
 */
export const useCreateCollectionEndpointApiSavedCollectionsPostHook = () => {
        const createCollectionEndpointApiSavedCollectionsPost = useCustomInstance<LibraryCollectionResponse>();

        return useCallback((
    libraryCollectionCreate: LibraryCollectionCreate,
 signal?: AbortSignal
) => {
        return createCollectionEndpointApiSavedCollectionsPost(
          {url: `/api/saved/collections`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: libraryCollectionCreate, signal
    },
          );
        }, [createCollectionEndpointApiSavedCollectionsPost])
      }



export const useCreateCollectionEndpointApiSavedCollectionsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateCollectionEndpointApiSavedCollectionsPostHook>>>, TError,{data: LibraryCollectionCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateCollectionEndpointApiSavedCollectionsPostHook>>>, TError,{data: LibraryCollectionCreate}, TContext> => {

const mutationKey = ['createCollectionEndpointApiSavedCollectionsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const createCollectionEndpointApiSavedCollectionsPost =  useCreateCollectionEndpointApiSavedCollectionsPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateCollectionEndpointApiSavedCollectionsPostHook>>>, {data: LibraryCollectionCreate}> = (props) => {
          const {data} = props ?? {};

          return  createCollectionEndpointApiSavedCollectionsPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCollectionEndpointApiSavedCollectionsPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateCollectionEndpointApiSavedCollectionsPostHook>>>>
    export type CreateCollectionEndpointApiSavedCollectionsPostMutationBody = LibraryCollectionCreate
    export type CreateCollectionEndpointApiSavedCollectionsPostMutationError = HTTPValidationError

    /**
 * @summary Create Collection Endpoint
 */
export const useCreateCollectionEndpointApiSavedCollectionsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateCollectionEndpointApiSavedCollectionsPostHook>>>, TError,{data: LibraryCollectionCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateCollectionEndpointApiSavedCollectionsPostHook>>>,
        TError,
        {data: LibraryCollectionCreate},
        TContext
      > => {
      return useMutation(useCreateCollectionEndpointApiSavedCollectionsPostMutationOptions(options), queryClient);
    }
    /**
 * Update a collection (e.g. rename, make public).
 * @summary Update Collection Endpoint
 */
export const useUpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchHook = () => {
        const updateCollectionEndpointApiSavedCollectionsCollectionIdPatch = useCustomInstance<LibraryCollectionResponse>();

        return useCallback((
    collectionId: string,
    libraryCollectionUpdate: LibraryCollectionUpdate,
 signal?: AbortSignal
) => {
        return updateCollectionEndpointApiSavedCollectionsCollectionIdPatch(
          {url: `/api/saved/collections/${collectionId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: libraryCollectionUpdate, signal
    },
          );
        }, [updateCollectionEndpointApiSavedCollectionsCollectionIdPatch])
      }



export const useUpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchHook>>>, TError,{collectionId: string;data: LibraryCollectionUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchHook>>>, TError,{collectionId: string;data: LibraryCollectionUpdate}, TContext> => {

const mutationKey = ['updateCollectionEndpointApiSavedCollectionsCollectionIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const updateCollectionEndpointApiSavedCollectionsCollectionIdPatch =  useUpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useUpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchHook>>>, {collectionId: string;data: LibraryCollectionUpdate}> = (props) => {
          const {collectionId,data} = props ?? {};

          return  updateCollectionEndpointApiSavedCollectionsCollectionIdPatch(collectionId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useUpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchHook>>>>
    export type UpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchMutationBody = LibraryCollectionUpdate
    export type UpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Collection Endpoint
 */
export const useUpdateCollectionEndpointApiSavedCollectionsCollectionIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchHook>>>, TError,{collectionId: string;data: LibraryCollectionUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useUpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchHook>>>,
        TError,
        {collectionId: string;data: LibraryCollectionUpdate},
        TContext
      > => {
      return useMutation(useUpdateCollectionEndpointApiSavedCollectionsCollectionIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Delete a library collection permanently.
 * @summary Delete Collection Endpoint
 */
export const useDeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteHook = () => {
        const deleteCollectionEndpointApiSavedCollectionsCollectionIdDelete = useCustomInstance<void>();

        return useCallback((
    collectionId: string,
 signal?: AbortSignal
) => {
        return deleteCollectionEndpointApiSavedCollectionsCollectionIdDelete(
          {url: `/api/saved/collections/${collectionId}`, method: 'DELETE', signal
    },
          );
        }, [deleteCollectionEndpointApiSavedCollectionsCollectionIdDelete])
      }



export const useDeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteHook>>>, TError,{collectionId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteHook>>>, TError,{collectionId: string}, TContext> => {

const mutationKey = ['deleteCollectionEndpointApiSavedCollectionsCollectionIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const deleteCollectionEndpointApiSavedCollectionsCollectionIdDelete =  useDeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteHook>>>, {collectionId: string}> = (props) => {
          const {collectionId} = props ?? {};

          return  deleteCollectionEndpointApiSavedCollectionsCollectionIdDelete(collectionId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteHook>>>>

    export type DeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Collection Endpoint
 */
export const useDeleteCollectionEndpointApiSavedCollectionsCollectionIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteHook>>>, TError,{collectionId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteHook>>>,
        TError,
        {collectionId: string},
        TContext
      > => {
      return useMutation(useDeleteCollectionEndpointApiSavedCollectionsCollectionIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Clone another user's public collection.
 * @summary Clone Collection Endpoint
 */
export const useCloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostHook = () => {
        const cloneCollectionEndpointApiSavedCollectionsCollectionIdClonePost = useCustomInstance<LibraryCollectionResponse>();

        return useCallback((
    collectionId: string,
 signal?: AbortSignal
) => {
        return cloneCollectionEndpointApiSavedCollectionsCollectionIdClonePost(
          {url: `/api/saved/collections/${collectionId}/clone`, method: 'POST', signal
    },
          );
        }, [cloneCollectionEndpointApiSavedCollectionsCollectionIdClonePost])
      }



export const useCloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostHook>>>, TError,{collectionId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostHook>>>, TError,{collectionId: string}, TContext> => {

const mutationKey = ['cloneCollectionEndpointApiSavedCollectionsCollectionIdClonePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const cloneCollectionEndpointApiSavedCollectionsCollectionIdClonePost =  useCloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostHook>>>, {collectionId: string}> = (props) => {
          const {collectionId} = props ?? {};

          return  cloneCollectionEndpointApiSavedCollectionsCollectionIdClonePost(collectionId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostHook>>>>

    export type CloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostMutationError = HTTPValidationError

    /**
 * @summary Clone Collection Endpoint
 */
export const useCloneCollectionEndpointApiSavedCollectionsCollectionIdClonePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostHook>>>, TError,{collectionId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostHook>>>,
        TError,
        {collectionId: string},
        TContext
      > => {
      return useMutation(useCloneCollectionEndpointApiSavedCollectionsCollectionIdClonePostMutationOptions(options), queryClient);
    }
    /**
 * Save a single resource to an existing collection.
 * @summary Save Resource To Collection Endpoint
 */
export const useSaveResourceToCollectionEndpointApiSavedCollectionItemPostHook = () => {
        const saveResourceToCollectionEndpointApiSavedCollectionItemPost = useCustomInstance<SavedResourceResponse>();

        return useCallback((
    saveResourceToCollectionRequest: SaveResourceToCollectionRequest,
 signal?: AbortSignal
) => {
        return saveResourceToCollectionEndpointApiSavedCollectionItemPost(
          {url: `/api/saved/collection-item`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: saveResourceToCollectionRequest, signal
    },
          );
        }, [saveResourceToCollectionEndpointApiSavedCollectionItemPost])
      }



export const useSaveResourceToCollectionEndpointApiSavedCollectionItemPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSaveResourceToCollectionEndpointApiSavedCollectionItemPostHook>>>, TError,{data: SaveResourceToCollectionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSaveResourceToCollectionEndpointApiSavedCollectionItemPostHook>>>, TError,{data: SaveResourceToCollectionRequest}, TContext> => {

const mutationKey = ['saveResourceToCollectionEndpointApiSavedCollectionItemPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const saveResourceToCollectionEndpointApiSavedCollectionItemPost =  useSaveResourceToCollectionEndpointApiSavedCollectionItemPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useSaveResourceToCollectionEndpointApiSavedCollectionItemPostHook>>>, {data: SaveResourceToCollectionRequest}> = (props) => {
          const {data} = props ?? {};

          return  saveResourceToCollectionEndpointApiSavedCollectionItemPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaveResourceToCollectionEndpointApiSavedCollectionItemPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSaveResourceToCollectionEndpointApiSavedCollectionItemPostHook>>>>
    export type SaveResourceToCollectionEndpointApiSavedCollectionItemPostMutationBody = SaveResourceToCollectionRequest
    export type SaveResourceToCollectionEndpointApiSavedCollectionItemPostMutationError = HTTPValidationError

    /**
 * @summary Save Resource To Collection Endpoint
 */
export const useSaveResourceToCollectionEndpointApiSavedCollectionItemPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSaveResourceToCollectionEndpointApiSavedCollectionItemPostHook>>>, TError,{data: SaveResourceToCollectionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useSaveResourceToCollectionEndpointApiSavedCollectionItemPostHook>>>,
        TError,
        {data: SaveResourceToCollectionRequest},
        TContext
      > => {
      return useMutation(useSaveResourceToCollectionEndpointApiSavedCollectionItemPostMutationOptions(options), queryClient);
    }
    /**
 * Remove a saved resource from library.
 * @summary Delete Saved Resource Endpoint
 */
export const useDeleteSavedResourceEndpointApiSavedIdDeleteHook = () => {
        const deleteSavedResourceEndpointApiSavedIdDelete = useCustomInstance<void>();

        return useCallback((
    id: string,
 signal?: AbortSignal
) => {
        return deleteSavedResourceEndpointApiSavedIdDelete(
          {url: `/api/saved/${id}`, method: 'DELETE', signal
    },
          );
        }, [deleteSavedResourceEndpointApiSavedIdDelete])
      }



export const useDeleteSavedResourceEndpointApiSavedIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteSavedResourceEndpointApiSavedIdDeleteHook>>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteSavedResourceEndpointApiSavedIdDeleteHook>>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteSavedResourceEndpointApiSavedIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const deleteSavedResourceEndpointApiSavedIdDelete =  useDeleteSavedResourceEndpointApiSavedIdDeleteHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDeleteSavedResourceEndpointApiSavedIdDeleteHook>>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteSavedResourceEndpointApiSavedIdDelete(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSavedResourceEndpointApiSavedIdDeleteMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDeleteSavedResourceEndpointApiSavedIdDeleteHook>>>>

    export type DeleteSavedResourceEndpointApiSavedIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Saved Resource Endpoint
 */
export const useDeleteSavedResourceEndpointApiSavedIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteSavedResourceEndpointApiSavedIdDeleteHook>>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDeleteSavedResourceEndpointApiSavedIdDeleteHook>>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(useDeleteSavedResourceEndpointApiSavedIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Add and scrape a custom link.
 * @summary Add Custom Link Endpoint
 */
export const useAddCustomLinkEndpointApiSavedLinkPostHook = () => {
        const addCustomLinkEndpointApiSavedLinkPost = useCustomInstance<SavedResourceResponse>();

        return useCallback((
    addCustomLinkRequest: AddCustomLinkRequest,
 signal?: AbortSignal
) => {
        return addCustomLinkEndpointApiSavedLinkPost(
          {url: `/api/saved/link`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addCustomLinkRequest, signal
    },
          );
        }, [addCustomLinkEndpointApiSavedLinkPost])
      }



export const useAddCustomLinkEndpointApiSavedLinkPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useAddCustomLinkEndpointApiSavedLinkPostHook>>>, TError,{data: AddCustomLinkRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useAddCustomLinkEndpointApiSavedLinkPostHook>>>, TError,{data: AddCustomLinkRequest}, TContext> => {

const mutationKey = ['addCustomLinkEndpointApiSavedLinkPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const addCustomLinkEndpointApiSavedLinkPost =  useAddCustomLinkEndpointApiSavedLinkPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useAddCustomLinkEndpointApiSavedLinkPostHook>>>, {data: AddCustomLinkRequest}> = (props) => {
          const {data} = props ?? {};

          return  addCustomLinkEndpointApiSavedLinkPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddCustomLinkEndpointApiSavedLinkPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useAddCustomLinkEndpointApiSavedLinkPostHook>>>>
    export type AddCustomLinkEndpointApiSavedLinkPostMutationBody = AddCustomLinkRequest
    export type AddCustomLinkEndpointApiSavedLinkPostMutationError = HTTPValidationError

    /**
 * @summary Add Custom Link Endpoint
 */
export const useAddCustomLinkEndpointApiSavedLinkPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useAddCustomLinkEndpointApiSavedLinkPostHook>>>, TError,{data: AddCustomLinkRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useAddCustomLinkEndpointApiSavedLinkPostHook>>>,
        TError,
        {data: AddCustomLinkRequest},
        TContext
      > => {
      return useMutation(useAddCustomLinkEndpointApiSavedLinkPostMutationOptions(options), queryClient);
    }
    /**
 * Batch evaluate unevaluated library resources within a preset+query group.
 * @summary Evaluate Saved Resources Endpoint
 */
export const useEvaluateSavedResourcesEndpointApiSavedEvaluatePostHook = () => {
        const evaluateSavedResourcesEndpointApiSavedEvaluatePost = useCustomInstance<EvaluateSavedResourcesEndpointApiSavedEvaluatePost200>();

        return useCallback((
    batchEvaluateRequest: BatchEvaluateRequest,
 signal?: AbortSignal
) => {
        return evaluateSavedResourcesEndpointApiSavedEvaluatePost(
          {url: `/api/saved/evaluate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: batchEvaluateRequest, signal
    },
          );
        }, [evaluateSavedResourcesEndpointApiSavedEvaluatePost])
      }



export const useEvaluateSavedResourcesEndpointApiSavedEvaluatePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useEvaluateSavedResourcesEndpointApiSavedEvaluatePostHook>>>, TError,{data: BatchEvaluateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useEvaluateSavedResourcesEndpointApiSavedEvaluatePostHook>>>, TError,{data: BatchEvaluateRequest}, TContext> => {

const mutationKey = ['evaluateSavedResourcesEndpointApiSavedEvaluatePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const evaluateSavedResourcesEndpointApiSavedEvaluatePost =  useEvaluateSavedResourcesEndpointApiSavedEvaluatePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useEvaluateSavedResourcesEndpointApiSavedEvaluatePostHook>>>, {data: BatchEvaluateRequest}> = (props) => {
          const {data} = props ?? {};

          return  evaluateSavedResourcesEndpointApiSavedEvaluatePost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EvaluateSavedResourcesEndpointApiSavedEvaluatePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useEvaluateSavedResourcesEndpointApiSavedEvaluatePostHook>>>>
    export type EvaluateSavedResourcesEndpointApiSavedEvaluatePostMutationBody = BatchEvaluateRequest
    export type EvaluateSavedResourcesEndpointApiSavedEvaluatePostMutationError = HTTPValidationError

    /**
 * @summary Evaluate Saved Resources Endpoint
 */
export const useEvaluateSavedResourcesEndpointApiSavedEvaluatePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useEvaluateSavedResourcesEndpointApiSavedEvaluatePostHook>>>, TError,{data: BatchEvaluateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useEvaluateSavedResourcesEndpointApiSavedEvaluatePostHook>>>,
        TError,
        {data: BatchEvaluateRequest},
        TContext
      > => {
      return useMutation(useEvaluateSavedResourcesEndpointApiSavedEvaluatePostMutationOptions(options), queryClient);
    }
    /**
 * Evaluate a single saved resource.
 * @summary Evaluate Single Resource Endpoint
 */
export const useEvaluateSingleResourceEndpointApiSavedEvaluateSinglePostHook = () => {
        const evaluateSingleResourceEndpointApiSavedEvaluateSinglePost = useCustomInstance<SavedResourceResponse>();

        return useCallback((
    evaluateSingleRequest: EvaluateSingleRequest,
 signal?: AbortSignal
) => {
        return evaluateSingleResourceEndpointApiSavedEvaluateSinglePost(
          {url: `/api/saved/evaluate-single`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: evaluateSingleRequest, signal
    },
          );
        }, [evaluateSingleResourceEndpointApiSavedEvaluateSinglePost])
      }



export const useEvaluateSingleResourceEndpointApiSavedEvaluateSinglePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useEvaluateSingleResourceEndpointApiSavedEvaluateSinglePostHook>>>, TError,{data: EvaluateSingleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useEvaluateSingleResourceEndpointApiSavedEvaluateSinglePostHook>>>, TError,{data: EvaluateSingleRequest}, TContext> => {

const mutationKey = ['evaluateSingleResourceEndpointApiSavedEvaluateSinglePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const evaluateSingleResourceEndpointApiSavedEvaluateSinglePost =  useEvaluateSingleResourceEndpointApiSavedEvaluateSinglePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useEvaluateSingleResourceEndpointApiSavedEvaluateSinglePostHook>>>, {data: EvaluateSingleRequest}> = (props) => {
          const {data} = props ?? {};

          return  evaluateSingleResourceEndpointApiSavedEvaluateSinglePost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EvaluateSingleResourceEndpointApiSavedEvaluateSinglePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useEvaluateSingleResourceEndpointApiSavedEvaluateSinglePostHook>>>>
    export type EvaluateSingleResourceEndpointApiSavedEvaluateSinglePostMutationBody = EvaluateSingleRequest
    export type EvaluateSingleResourceEndpointApiSavedEvaluateSinglePostMutationError = HTTPValidationError

    /**
 * @summary Evaluate Single Resource Endpoint
 */
export const useEvaluateSingleResourceEndpointApiSavedEvaluateSinglePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useEvaluateSingleResourceEndpointApiSavedEvaluateSinglePostHook>>>, TError,{data: EvaluateSingleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useEvaluateSingleResourceEndpointApiSavedEvaluateSinglePostHook>>>,
        TError,
        {data: EvaluateSingleRequest},
        TContext
      > => {
      return useMutation(useEvaluateSingleResourceEndpointApiSavedEvaluateSinglePostMutationOptions(options), queryClient);
    }
