/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Federated search across DuckDuckGo, YouTube, and OpenAlex.

Rate limited to 20 requests per minute per user.
Source labels: ddgs=DuckDuckGo, youtube=YouTube, openalex=OpenAlex
 * @summary Search
 */
export const searchApiDiscoverySearchPostBodyQueryMax = 500;



export const SearchApiDiscoverySearchPostBody = zod.object({
  "preset_id": zod.uuid(),
  "query": zod.string().min(1).max(searchApiDiscoverySearchPostBodyQueryMax)
}).describe('Request body for federated search.')

export const searchApiDiscoverySearchPostResponseResultsItemMetadataOneSourceDefault = `ddgs`;
export const searchApiDiscoverySearchPostResponseResultsItemMetadataTwoSourceDefault = `youtube`;
export const searchApiDiscoverySearchPostResponseResultsItemMetadataTwoDurationDefault = ``;
export const searchApiDiscoverySearchPostResponseResultsItemMetadataThreeSourceDefault = `openalex`;

export const SearchApiDiscoverySearchPostResponse = zod.object({
  "query": zod.string(),
  "preset_id": zod.uuid(),
  "total_results": zod.number(),
  "counts_by_source": zod.record(zod.string(), zod.number()),
  "results": zod.array(zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(searchApiDiscoverySearchPostResponseResultsItemMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(searchApiDiscoverySearchPostResponseResultsItemMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(searchApiDiscoverySearchPostResponseResultsItemMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(searchApiDiscoverySearchPostResponseResultsItemMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.')])
}).describe('Normalised resource card returned by all providers.')),
  "errors": zod.array(zod.object({
  "source": zod.enum(['ddgs', 'youtube', 'openalex']),
  "message": zod.string()
}).describe('Error from a single search provider.'))
}).describe('Unified federated search response.')

