/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Federated search across DuckDuckGo, YouTube, and OpenAlex.

Rate limited to 20 requests per minute per user.
Source labels: ddgs=DuckDuckGo, youtube=YouTube, openalex=OpenAlex
 * @summary Search
 */
export const searchApiDiscoverySearchGetQueryQueryMax = 500;



export const SearchApiDiscoverySearchGetQueryParams = zod.object({
  "preset_id": zod.uuid(),
  "query": zod.string().min(1).max(searchApiDiscoverySearchGetQueryQueryMax)
})

export const searchApiDiscoverySearchGetResponseResultsItemMetadataOneSourceDefault = `ddgs`;
export const searchApiDiscoverySearchGetResponseResultsItemMetadataTwoSourceDefault = `youtube`;
export const searchApiDiscoverySearchGetResponseResultsItemMetadataTwoDurationDefault = ``;
export const searchApiDiscoverySearchGetResponseResultsItemMetadataThreeSourceDefault = `openalex`;
export const searchApiDiscoverySearchGetResponseEvaluationsItemOverallScoreMin = 0;
export const searchApiDiscoverySearchGetResponseEvaluationsItemOverallScoreMax = 10;

export const searchApiDiscoverySearchGetResponseEvaluationsItemScoresScoreMax = 10;

export const searchApiDiscoverySearchGetResponseEvaluationsItemScoresMaxDefault = 10;

export const SearchApiDiscoverySearchGetResponse = zod.object({
  "query": zod.string(),
  "preset_id": zod.uuid(),
  "total_results": zod.number(),
  "counts_by_source": zod.record(zod.string(), zod.number()),
  "results": zod.array(zod.object({
  "title": zod.string(),
  "url": zod.string(),
  "source": zod.enum(['ddgs', 'youtube', 'openalex']),
  "type": zod.enum(['webpage', 'video', 'paper']),
  "snippet": zod.string(),
  "thumbnail_url": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.union([zod.object({
  "source": zod.literal("ddgs").default(searchApiDiscoverySearchGetResponseResultsItemMetadataOneSourceDefault),
  "domain": zod.string(),
  "published_date": zod.union([zod.string(),zod.null()]).optional(),
  "language": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from DuckDuckGo search results.'),zod.object({
  "source": zod.literal("youtube").default(searchApiDiscoverySearchGetResponseResultsItemMetadataTwoSourceDefault),
  "channel": zod.string(),
  "duration": zod.string().default(searchApiDiscoverySearchGetResponseResultsItemMetadataTwoDurationDefault),
  "view_count": zod.union([zod.number(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from YouTube Data API results.'),zod.object({
  "source": zod.literal("openalex").default(searchApiDiscoverySearchGetResponseResultsItemMetadataThreeSourceDefault),
  "authors": zod.array(zod.string()).optional(),
  "journal": zod.union([zod.string(),zod.null()]).optional(),
  "citation_count": zod.union([zod.number(),zod.null()]).optional(),
  "doi": zod.union([zod.string(),zod.null()]).optional(),
  "published_date": zod.union([zod.string(),zod.null()]).optional()
}).describe('Metadata from OpenAlex works results.')]),
  "relevance_score": zod.union([zod.number(),zod.null()]).optional(),
  "relevance_reason": zod.union([zod.string(),zod.null()]).optional(),
  "evaluation_details": zod.union([zod.record(zod.string(), zod.record(zod.string(), zod.unknown())),zod.null()]).optional().describe('Detailed dimension scores')
}).describe('Normalised resource card returned by all providers.')),
  "errors": zod.array(zod.object({
  "source": zod.enum(['ddgs', 'youtube', 'openalex']),
  "message": zod.string()
}).describe('Error from a single search provider.')),
  "evaluations": zod.array(zod.object({
  "resource_url": zod.string(),
  "overall_score": zod.number().min(searchApiDiscoverySearchGetResponseEvaluationsItemOverallScoreMin).max(searchApiDiscoverySearchGetResponseEvaluationsItemOverallScoreMax),
  "relevance_reason": zod.string(),
  "recommended_use": zod.enum(['primary_resource', 'supplementary', 'reference_only']),
  "scores": zod.record(zod.string(), zod.object({
  "score": zod.number().min(1).max(searchApiDiscoverySearchGetResponseEvaluationsItemScoresScoreMax),
  "max": zod.number().default(searchApiDiscoverySearchGetResponseEvaluationsItemScoresMaxDefault),
  "reason": zod.string()
}).describe('Score for a single evaluation dimension.'))
}).describe('Full evaluation of a single resource across 7 dimensions.')).optional()
}).describe('Extends SearchResponse with evaluation data for the top 4 results.')

