/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * A concrete adaptation the teacher can apply.
 */
export interface AdaptationSuggestion {
  action: string;
  rationale: string;
}
