/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

export interface AddCustomLinkRequest {
  preset_id: string;
  search_query: string;
  /**
     * @minLength 1
     * @maxLength 2083
     */
  url: string;
  title?: string | null;
}
