/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { AdversarialFlagCategory } from './adversarial-flag-category';
import type { AdversarialFlagSeverity } from './adversarial-flag-severity';

/**
 * Single issue raised by the adversarial reviewer.
 */
export interface AdversarialFlag {
  category: AdversarialFlagCategory;
  severity: AdversarialFlagSeverity;
  explanation: string;
  suggested_action: string;
}
