/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

export type AdversarialFlagCategory = typeof AdversarialFlagCategory[keyof typeof AdversarialFlagCategory];


export const AdversarialFlagCategory = {
  false_positive: 'false_positive',
  hidden_bias: 'hidden_bias',
  accuracy_gap: 'accuracy_gap',
  safety: 'safety',
  licensing_trap: 'licensing_trap',
} as const;
