/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Metadata from manually added custom links.
 */
export interface CustomMetadata {
  source?: 'custom';
  domain: string;
  og_title?: string | null;
  og_description?: string | null;
  og_image?: string | null;
}
