/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Metadata from DuckDuckGo search results.
 */
export interface DdgsMetadata {
  source?: 'ddgs';
  domain: string;
  published_date?: string | null;
  language?: string | null;
}
