/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Score for a single evaluation dimension.
 */
export interface DimensionScore {
  /**
     * @minimum 1
     * @maximum 10
     */
  score: number;
  max?: number;
  reason: string;
}
