/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { EvaluatedSearchResponseCountsBySource } from './evaluated-search-response-counts-by-source';
import type { EvaluationResult } from './evaluation-result';
import type { ResourceCard } from './resource-card';
import type { SourceError } from './source-error';

/**
 * Extends SearchResponse with evaluation data for the top 4 results.
 */
export interface EvaluatedSearchResponse {
  query: string;
  preset_id: string;
  total_results: number;
  counts_by_source: EvaluatedSearchResponseCountsBySource;
  results: ResourceCard[];
  errors: SourceError[];
  evaluations?: EvaluationResult[];
}
