/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { GenerateArtifactRequestArtifactType } from './generate-artifact-request-artifact-type';
import type { GenerationOptions } from './generation-options';

export interface GenerateArtifactRequest {
  preset_id: string;
  /**
     * @minItems 1
     * @maxItems 10
     */
  saved_resource_ids: string[];
  artifact_type: GenerateArtifactRequestArtifactType;
  options?: GenerationOptions | null;
}
