/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

export type GenerateArtifactRequestArtifactType = typeof GenerateArtifactRequestArtifactType[keyof typeof GenerateArtifactRequestArtifactType];


export const GenerateArtifactRequestArtifactType = {
  quiz: 'quiz',
  mindmap: 'mindmap',
  summary: 'summary',
  flashcards: 'flashcards',
  study_guide: 'study_guide',
  briefing_doc: 'briefing_doc',
} as const;
