/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { GeneratedArtifactResponseContent } from './generated-artifact-response-content';

export interface GeneratedArtifactResponse {
  id: string;
  preset_id: string;
  artifact_type: string;
  content: GeneratedArtifactResponseContent;
  source_resource_ids: string[];
  created_at: string;
}
