/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { HealthResponseServices } from './health-response-services';
import type { HealthResponseStatus } from './health-response-status';

/**
 * Health check response with detailed service statuses.
 */
export interface HealthResponse {
  status: HealthResponseStatus;
  version?: string;
  services: HealthResponseServices;
}
