/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

export type HealthResponseStatus = typeof HealthResponseStatus[keyof typeof HealthResponseStatus];


export const HealthResponseStatus = {
  healthy: 'healthy',
  degraded: 'degraded',
  unhealthy: 'unhealthy',
} as const;
