/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationError } from './validation-error';

export interface HTTPValidationError {
  detail?: ValidationError[];
}
