/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Internal token exchange — pre-verified by Next.js server.
 */
export interface InternalExchangeRequest {
  email: string;
  name?: string | null;
}
