/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { GeneratedSearchQueries } from './generated-search-queries';
import type { JudgedSearchResponseCountsBySource } from './judged-search-response-counts-by-source';
import type { JudgmentResult } from './judgment-result';
import type { ResourceCard } from './resource-card';
import type { SourceError } from './source-error';

/**
 * Extends SearchResponse with judgment data for the top results.
 */
export interface JudgedSearchResponse {
  query: string;
  preset_id: string;
  total_results: number;
  counts_by_source: JudgedSearchResponseCountsBySource;
  results: ResourceCard[];
  errors: SourceError[];
  generated_queries?: GeneratedSearchQueries | null;
  judgments?: JudgmentResult[];
  /** Opaque ID for Phase 2 per-resource evaluation requests. */
  search_id?: string | null;
}
