/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

export interface LibraryCollectionResponse {
  id: string;
  user_id: string;
  preset_id: string;
  search_query: string;
  name: string;
  is_public: boolean;
  clone_count: number;
  created_at: string;
}
