/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

export interface LibraryCollectionUpdate {
  name?: string | null;
  is_public?: boolean | null;
}
