/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

export type ListSavedResourcesEndpointApiSavedGetParams = {
preset_id?: string | null;
};
