/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type OAuthLoginRequestProvider = typeof OAuthLoginRequestProvider[keyof typeof OAuthLoginRequestProvider];


export const OAuthLoginRequestProvider = {
  google: 'google',
  github: 'github',
  facebook: 'facebook',
} as const;
