/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { SavedResourceResponse } from './saved-resource-response';

export interface PresetGroup {
  preset_id: string;
  preset_name: string;
  preset_subject: string;
  preset_topic?: string | null;
  items: SavedResourceResponse[];
}
