/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { PresetResponseSourceWeights } from './preset-response-source-weights';

/**
 * Schema for preset response including id and timestamps.
 */
export interface PresetResponse {
  id: string;
  user_id: string;
  is_default: boolean;
  name: string;
  curriculum_framework: string | null;
  subject: string;
  year_level: string;
  topic: string | null;
  country: string;
  state_region: string | null;
  city: string | null;
  teaching_language: string;
  class_size: number | null;
  eal_d_students: number | null;
  reading_support_students: number | null;
  extension_students: number | null;
  student_interests: unknown[];
  language_backgrounds: unknown[];
  average_reading_level: string | null;
  source_weights: PresetResponseSourceWeights;
  additional_notes: string | null;
  created_at: string;
  updated_at: string;
}
