/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Refresh token request.
 */
export interface RefreshTokenRequest {
  refresh_token: string;
}
