/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Registration response — tokens if no verification needed.
 */
export interface RegisterResponse {
  access_token?: string | null;
  refresh_token?: string | null;
  requires_verification?: boolean;
  message: string;
}
