/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

export type ResourceCardSource = typeof ResourceCardSource[keyof typeof ResourceCardSource];


export const ResourceCardSource = {
  ddgs: 'ddgs',
  youtube: 'youtube',
  openalex: 'openalex',
  custom: 'custom',
} as const;
