/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

export type ResourceCardType = typeof ResourceCardType[keyof typeof ResourceCardType];


export const ResourceCardType = {
  webpage: 'webpage',
  video: 'video',
  paper: 'paper',
} as const;
