/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { DdgsMetadata } from './ddgs-metadata';
import type { OpenAlexMetadata } from './open-alex-metadata';
import type { ResourceCardSource } from './resource-card-source';
import type { ResourceCardType } from './resource-card-type';
import type { YoutubeMetadata } from './youtube-metadata';

/**
 * Normalised resource card returned by all providers.
 */
export interface ResourceCard {
  title: string;
  url: string;
  source: ResourceCardSource;
  type: ResourceCardType;
  snippet: string;
  thumbnail_url?: string | null;
  metadata: DdgsMetadata | YoutubeMetadata | OpenAlexMetadata;
}
