/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { EvaluationResultInput } from './evaluation-result-input';
import type { ResourceCard } from './resource-card';

export interface SaveResourceToCollectionRequest {
  collection_id: string;
  resource: ResourceCard;
  evaluation_data?: EvaluationResultInput | null;
}
