/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { EvaluationResultOutput } from './evaluation-result-output';
import type { ResourceCard } from './resource-card';

export interface SavedResourceResponse {
  id: string;
  preset_id: string;
  search_query: string;
  resource_url: string;
  resource_data: ResourceCard;
  evaluation_data: EvaluationResultOutput | null;
  saved_at: string;
}
