/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body for federated search.
 */
export interface SearchRequest {
  preset_id: string;
  /**
     * @minLength 1
     * @maxLength 500
     */
  query: string;
}
