/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { ServiceStatusStatus } from './service-status-status';

/**
 * Individual service health status.
 */
export interface ServiceStatus {
  status: ServiceStatusStatus;
  latency_ms?: number | null;
  error?: string | null;
}
