/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Exchange better-auth session token for backend JWE tokens.
 */
export interface SessionExchangeRequest {
  session_token: string;
}
