/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Source weights for federated search result distribution.
 */
export interface SourceWeights {
  /**
     * @minimum 0
     * @maximum 1
     */
  ddgs?: number;
  /**
     * @minimum 0
     * @maximum 1
     */
  youtube?: number;
  /**
     * @minimum 0
     * @maximum 1
     */
  openalex?: number;
}
