/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { SourceErrorSource } from './source-error-source';

/**
 * Error from a single search provider.
 */
export interface SourceError {
  source: SourceErrorSource;
  message: string;
}
