/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryCollectionResponse } from './library-collection-response';
import type { SavedResourceResponse } from './saved-resource-response';

export interface SuggestedCollectionResponse {
  collection: LibraryCollectionResponse;
  matched_by: string;
  resources_count?: number;
  publisher_name?: string | null;
  is_cloned_by_user?: boolean;
  resources?: SavedResourceResponse[];
}
