/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Token response.
 */
export interface TokenResponse {
  access_token: string;
  refresh_token: string;
  token_type?: string;
}
