/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * User response model.
 */
export interface UserResponse {
  id: string;
  email: string;
  name?: string | null;
  image?: string | null;
  email_verified?: boolean;
  created_at: string;
  updated_at: string;
}
