/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Metadata from YouTube Data API results.
 */
export interface YoutubeMetadata {
  source?: 'youtube';
  channel: string;
  duration?: string;
  view_count?: number | null;
  published_date?: string | null;
}
