/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * OAuth login endpoint.

Verify OAuth token, create/update user, and issue JWE tokens.
 * @summary Login
 */
export const LoginApiAuthLoginPostBody = zod.object({
  "provider": zod.enum(['google', 'github', 'facebook']),
  "access_token": zod.string(),
  "email": zod.string(),
  "name": zod.union([zod.string(),zod.null()]).optional()
}).describe('OAuth login request.')

export const loginApiAuthLoginPostResponseTokenTypeDefault = `bearer`;

export const LoginApiAuthLoginPostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(loginApiAuthLoginPostResponseTokenTypeDefault)
}).describe('Token response.')

/**
 * Exchange better-auth session token for backend JWE tokens.

Used by email/password auth users who have no OAuth provider token.
Verifies session with better-auth server, then issues backend tokens.
 * @summary Session Exchange
 */
export const SessionExchangeApiAuthSessionExchangePostBody = zod.object({
  "session_token": zod.string()
}).describe('Exchange better-auth session token for backend JWE tokens.')

export const sessionExchangeApiAuthSessionExchangePostResponseTokenTypeDefault = `bearer`;

export const SessionExchangeApiAuthSessionExchangePostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(sessionExchangeApiAuthSessionExchangePostResponseTokenTypeDefault)
}).describe('Token response.')

/**
 * Internal token exchange for pre-verified sessions.

Called by Next.js API route after server-side session verification.
Creates/finds user and issues backend JWE tokens.
 * @summary Internal Exchange
 */
export const InternalExchangeApiAuthInternalExchangePostBody = zod.object({
  "email": zod.string(),
  "name": zod.union([zod.string(),zod.null()]).optional()
}).describe('Internal token exchange — pre-verified by Next.js server.')

export const internalExchangeApiAuthInternalExchangePostResponseTokenTypeDefault = `bearer`;

export const InternalExchangeApiAuthInternalExchangePostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(internalExchangeApiAuthInternalExchangePostResponseTokenTypeDefault)
}).describe('Token response.')

/**
 * Refresh access token using refresh token.
 * @summary Refresh Token
 */
export const RefreshTokenApiAuthRefreshPostBody = zod.object({
  "refresh_token": zod.string()
}).describe('Refresh token request.')

export const refreshTokenApiAuthRefreshPostResponseTokenTypeDefault = `bearer`;

export const RefreshTokenApiAuthRefreshPostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(refreshTokenApiAuthRefreshPostResponseTokenTypeDefault)
}).describe('Token response.')

