/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Register a new user with email and password.
 * @summary Register
 */
export const RegisterApiAuthRegisterPostBody = zod.object({
  "email": zod.string(),
  "password": zod.string(),
  "name": zod.union([zod.string(),zod.null()]).optional()
}).describe('Email\/password registration.')

/**
 * Login with email and password.
 * @summary Email Login
 */
export const EmailLoginApiAuthEmailLoginPostBody = zod.object({
  "email": zod.string(),
  "password": zod.string()
}).describe('Email\/password login.')

export const emailLoginApiAuthEmailLoginPostResponseTokenTypeDefault = `bearer`;

export const EmailLoginApiAuthEmailLoginPostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(emailLoginApiAuthEmailLoginPostResponseTokenTypeDefault)
}).describe('Token response.')

/**
 * OAuth login endpoint.

Verify OAuth token, create/update user, and issue JWE tokens.
 * @summary Oauth Login
 */
export const OauthLoginApiAuthLoginPostBody = zod.object({
  "provider": zod.enum(['google', 'github', 'facebook']),
  "access_token": zod.string(),
  "email": zod.string(),
  "name": zod.union([zod.string(),zod.null()]).optional()
}).describe('OAuth login request.')

export const oauthLoginApiAuthLoginPostResponseTokenTypeDefault = `bearer`;

export const OauthLoginApiAuthLoginPostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(oauthLoginApiAuthLoginPostResponseTokenTypeDefault)
}).describe('Token response.')

/**
 * Refresh access token using refresh token.
 * @summary Refresh Token
 */
export const RefreshTokenApiAuthRefreshPostBody = zod.object({
  "refresh_token": zod.string()
}).describe('Refresh token request.')

export const refreshTokenApiAuthRefreshPostResponseTokenTypeDefault = `bearer`;

export const RefreshTokenApiAuthRefreshPostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(refreshTokenApiAuthRefreshPostResponseTokenTypeDefault)
}).describe('Token response.')

