/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Return the profile of the currently authenticated user.
 * @summary Get Current User Profile
 */
export const getCurrentUserProfileApiUsersMeGetResponseEmailVerifiedDefault = false;

export const GetCurrentUserProfileApiUsersMeGetResponse = zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "image": zod.union([zod.string(),zod.null()]).optional(),
  "email_verified": zod.boolean().default(getCurrentUserProfileApiUsersMeGetResponseEmailVerifiedDefault),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('User response model.')

