"""add cloned_from_id to library_collections

Revision ID: 156885046efb
Revises: 5899875c22d2
Create Date: 2026-04-08 02:16:51.058608

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "156885046efb"
down_revision: str | None = "5899875c22d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "library_collections", sa.Column("cloned_from_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_library_collections_cloned_from_id_library_collections"),
        "library_collections",
        "library_collections",
        ["cloned_from_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_library_collections_cloned_from_id_library_collections"),
        "library_collections",
        type_="foreignkey",
    )
    op.drop_column("library_collections", "cloned_from_id")
    # ### end Alembic commands ###
