"""add resource_evaluations table

Revision ID: 230b7e291e5c
Revises: 465be38b13e8
Create Date: 2026-04-08 06:12:17.945376

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '230b7e291e5c'
down_revision: str | None = '465be38b13e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_evaluations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preset_id', sa.Uuid(), nullable=False),
    sa.Column('resource_url', sa.Text(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('judgment_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_evaluations'))
    )
    op.create_index('ix_resource_evaluations_lookup', 'resource_evaluations', ['preset_id', 'resource_url', 'search_query'], unique=False)
    op.create_index('ix_resource_evaluations_user_id', 'resource_evaluations', ['user_id'], unique=False)
    op.alter_column('classroom_presets', 'student_interests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('classroom_presets', 'language_backgrounds',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classroom_presets', 'language_backgrounds',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('classroom_presets', 'student_interests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_resource_evaluations_user_id', table_name='resource_evaluations')
    op.drop_index('ix_resource_evaluations_lookup', table_name='resource_evaluations')
    op.drop_table('resource_evaluations')
    # ### end Alembic commands ###
