"""add resource_evaluations table

Revision ID: 30d7f3982ea9
Revises: 230b7e291e5c
Create Date: 2026-04-08 06:14:17.023623

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '30d7f3982ea9'
down_revision: str | None = '230b7e291e5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
