"""Add search_query to saved_resources

Revision ID: afb2e6fe8ebf
Revises: bcddadb2147a
Create Date: 2026-04-06 21:01:56.961403

"""

import sqlalchemy as sa

from alembic import op

revision: str = "afb2e6fe8ebf"
down_revision: str | None = "c3d4e5f6a7b8"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "saved_resources",
        sa.Column(
            "search_query", sa.String(length=512), server_default="", nullable=False
        ),
    )
    op.drop_constraint(op.f("uq_saved_resource"), "saved_resources", type_="unique")
    op.create_unique_constraint(
        "uq_saved_resource_v2",
        "saved_resources",
        ["user_id", "preset_id", "search_query", "resource_url"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_saved_resource_v2", "saved_resources", type_="unique")
    op.create_unique_constraint(
        op.f("uq_saved_resource"),
        "saved_resources",
        ["user_id", "preset_id", "resource_url"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("saved_resources", "search_query")
    # ### end Alembic commands ###
