"""Add saved_resources table

Revision ID: bcddadb2147a
Revises: b2c3d4e5f6a7
Create Date: 2026-04-06 18:46:33.527672

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcddadb2147a"
down_revision: str | None = "b2c3d4e5f6a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_resources",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("preset_id", sa.Uuid(), nullable=False),
        sa.Column("resource_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "resource_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "evaluation_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "saved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["preset_id"],
            ["classroom_presets.id"],
            name=op.f("fk_saved_resources_preset_id_classroom_presets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_saved_resources_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_resources")),
        sa.UniqueConstraint(
            "user_id", "preset_id", "resource_url", name="uq_saved_resource"
        ),
    )
    op.create_index(
        "ix_saved_resources_user_preset",
        "saved_resources",
        ["user_id", "preset_id"],
        unique=False,
    )
    op.alter_column(
        "classroom_presets",
        "student_interests",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "classroom_presets",
        "language_backgrounds",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "classroom_presets",
        "language_backgrounds",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "classroom_presets",
        "student_interests",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_index("ix_saved_resources_user_preset", table_name="saved_resources")
    op.drop_table("saved_resources")
    # ### end Alembic commands ###
