/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * edcurate-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Create a new classroom preset.
 * @summary Create Preset
 */
export const createPresetApiPresetsPostBodyNameMax = 255;

export const createPresetApiPresetsPostBodyIsDefaultDefault = false;
export const createPresetApiPresetsPostBodyCurriculumFrameworkOneMax = 255;

export const createPresetApiPresetsPostBodySubjectMax = 255;

export const createPresetApiPresetsPostBodyYearLevelMax = 50;

export const createPresetApiPresetsPostBodyCountryMax = 100;

export const createPresetApiPresetsPostBodyStateRegionOneMax = 100;

export const createPresetApiPresetsPostBodyCityOneMax = 100;

export const createPresetApiPresetsPostBodyTeachingLanguageDefault = `en`;
export const createPresetApiPresetsPostBodyTeachingLanguageMin = 2;
export const createPresetApiPresetsPostBodyTeachingLanguageMax = 10;

export const createPresetApiPresetsPostBodyClassSizeOneExclusiveMin = 0;

export const createPresetApiPresetsPostBodyEalDStudentsOneMin = 0;

export const createPresetApiPresetsPostBodyReadingSupportStudentsOneMin = 0;

export const createPresetApiPresetsPostBodyExtensionStudentsOneMin = 0;

export const createPresetApiPresetsPostBodyAverageReadingLevelOneMax = 50;

export const createPresetApiPresetsPostBodySourceWeightsDdgsDefault = 0.34;
export const createPresetApiPresetsPostBodySourceWeightsDdgsMin = 0;
export const createPresetApiPresetsPostBodySourceWeightsDdgsMax = 1;

export const createPresetApiPresetsPostBodySourceWeightsYoutubeDefault = 0.33;
export const createPresetApiPresetsPostBodySourceWeightsYoutubeMin = 0;
export const createPresetApiPresetsPostBodySourceWeightsYoutubeMax = 1;

export const createPresetApiPresetsPostBodySourceWeightsOpenalexDefault = 0.33;
export const createPresetApiPresetsPostBodySourceWeightsOpenalexMin = 0;
export const createPresetApiPresetsPostBodySourceWeightsOpenalexMax = 1;



export const CreatePresetApiPresetsPostBody = zod.object({
  "name": zod.string().min(1).max(createPresetApiPresetsPostBodyNameMax),
  "is_default": zod.boolean().default(createPresetApiPresetsPostBodyIsDefaultDefault),
  "curriculum_framework": zod.union([zod.string().max(createPresetApiPresetsPostBodyCurriculumFrameworkOneMax),zod.null()]).optional(),
  "subject": zod.string().min(1).max(createPresetApiPresetsPostBodySubjectMax),
  "year_level": zod.string().min(1).max(createPresetApiPresetsPostBodyYearLevelMax),
  "country": zod.string().min(1).max(createPresetApiPresetsPostBodyCountryMax),
  "state_region": zod.union([zod.string().max(createPresetApiPresetsPostBodyStateRegionOneMax),zod.null()]).optional(),
  "city": zod.union([zod.string().max(createPresetApiPresetsPostBodyCityOneMax),zod.null()]).optional(),
  "teaching_language": zod.string().min(createPresetApiPresetsPostBodyTeachingLanguageMin).max(createPresetApiPresetsPostBodyTeachingLanguageMax).default(createPresetApiPresetsPostBodyTeachingLanguageDefault),
  "class_size": zod.union([zod.number().gt(createPresetApiPresetsPostBodyClassSizeOneExclusiveMin),zod.null()]).optional(),
  "eal_d_students": zod.union([zod.number().min(createPresetApiPresetsPostBodyEalDStudentsOneMin),zod.null()]).optional(),
  "reading_support_students": zod.union([zod.number().min(createPresetApiPresetsPostBodyReadingSupportStudentsOneMin),zod.null()]).optional(),
  "extension_students": zod.union([zod.number().min(createPresetApiPresetsPostBodyExtensionStudentsOneMin),zod.null()]).optional(),
  "student_interests": zod.array(zod.string()).optional(),
  "language_backgrounds": zod.array(zod.string()).optional(),
  "average_reading_level": zod.union([zod.string().max(createPresetApiPresetsPostBodyAverageReadingLevelOneMax),zod.null()]).optional(),
  "source_weights": zod.object({
  "ddgs": zod.number().min(createPresetApiPresetsPostBodySourceWeightsDdgsMin).max(createPresetApiPresetsPostBodySourceWeightsDdgsMax).default(createPresetApiPresetsPostBodySourceWeightsDdgsDefault),
  "youtube": zod.number().min(createPresetApiPresetsPostBodySourceWeightsYoutubeMin).max(createPresetApiPresetsPostBodySourceWeightsYoutubeMax).default(createPresetApiPresetsPostBodySourceWeightsYoutubeDefault),
  "openalex": zod.number().min(createPresetApiPresetsPostBodySourceWeightsOpenalexMin).max(createPresetApiPresetsPostBodySourceWeightsOpenalexMax).default(createPresetApiPresetsPostBodySourceWeightsOpenalexDefault)
}).optional().describe('Source weights for federated search result distribution.'),
  "additional_notes": zod.union([zod.string(),zod.null()]).optional()
}).describe('Schema for creating a classroom preset.')

/**
 * List classroom presets for the current user (paginated).
 * @summary List Presets
 */
export const listPresetsApiPresetsGetQueryPageDefault = 1;

export const listPresetsApiPresetsGetQueryLimitDefault = 20;
export const listPresetsApiPresetsGetQueryLimitMax = 100;



export const ListPresetsApiPresetsGetQueryParams = zod.object({
  "page": zod.number().min(1).default(listPresetsApiPresetsGetQueryPageDefault),
  "limit": zod.number().min(1).max(listPresetsApiPresetsGetQueryLimitMax).default(listPresetsApiPresetsGetQueryLimitDefault)
})

export const ListPresetsApiPresetsGetResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.uuid(),
  "user_id": zod.uuid(),
  "is_default": zod.boolean(),
  "name": zod.string(),
  "curriculum_framework": zod.union([zod.string(),zod.null()]),
  "subject": zod.string(),
  "year_level": zod.string(),
  "country": zod.string(),
  "state_region": zod.union([zod.string(),zod.null()]),
  "city": zod.union([zod.string(),zod.null()]),
  "teaching_language": zod.string(),
  "class_size": zod.union([zod.number(),zod.null()]),
  "eal_d_students": zod.union([zod.number(),zod.null()]),
  "reading_support_students": zod.union([zod.number(),zod.null()]),
  "extension_students": zod.union([zod.number(),zod.null()]),
  "student_interests": zod.array(zod.unknown()),
  "language_backgrounds": zod.array(zod.unknown()),
  "average_reading_level": zod.union([zod.string(),zod.null()]),
  "source_weights": zod.record(zod.string(), zod.unknown()),
  "additional_notes": zod.union([zod.string(),zod.null()]),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('Schema for preset response including id and timestamps.')),
  "meta": zod.object({
  "page": zod.number().describe('Current page number'),
  "limit": zod.number().describe('Items per page'),
  "total": zod.number().describe('Total number of items'),
  "total_pages": zod.number().describe('Total number of pages'),
  "has_next": zod.boolean().describe('Whether there is a next page'),
  "has_prev": zod.boolean().describe('Whether there is a previous page')
}).describe('Pagination metadata.')
})

/**
 * Get a single classroom preset by id.
 * @summary Get Preset
 */
export const GetPresetApiPresetsPresetIdGetParams = zod.object({
  "preset_id": zod.uuid()
})

export const GetPresetApiPresetsPresetIdGetResponse = zod.object({
  "id": zod.uuid(),
  "user_id": zod.uuid(),
  "is_default": zod.boolean(),
  "name": zod.string(),
  "curriculum_framework": zod.union([zod.string(),zod.null()]),
  "subject": zod.string(),
  "year_level": zod.string(),
  "country": zod.string(),
  "state_region": zod.union([zod.string(),zod.null()]),
  "city": zod.union([zod.string(),zod.null()]),
  "teaching_language": zod.string(),
  "class_size": zod.union([zod.number(),zod.null()]),
  "eal_d_students": zod.union([zod.number(),zod.null()]),
  "reading_support_students": zod.union([zod.number(),zod.null()]),
  "extension_students": zod.union([zod.number(),zod.null()]),
  "student_interests": zod.array(zod.unknown()),
  "language_backgrounds": zod.array(zod.unknown()),
  "average_reading_level": zod.union([zod.string(),zod.null()]),
  "source_weights": zod.record(zod.string(), zod.unknown()),
  "additional_notes": zod.union([zod.string(),zod.null()]),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('Schema for preset response including id and timestamps.')

/**
 * Full update of a classroom preset.
 * @summary Update Preset
 */
export const UpdatePresetApiPresetsPresetIdPutParams = zod.object({
  "preset_id": zod.uuid()
})

export const updatePresetApiPresetsPresetIdPutBodyNameMax = 255;

export const updatePresetApiPresetsPresetIdPutBodyIsDefaultDefault = false;
export const updatePresetApiPresetsPresetIdPutBodyCurriculumFrameworkOneMax = 255;

export const updatePresetApiPresetsPresetIdPutBodySubjectMax = 255;

export const updatePresetApiPresetsPresetIdPutBodyYearLevelMax = 50;

export const updatePresetApiPresetsPresetIdPutBodyCountryMax = 100;

export const updatePresetApiPresetsPresetIdPutBodyStateRegionOneMax = 100;

export const updatePresetApiPresetsPresetIdPutBodyCityOneMax = 100;

export const updatePresetApiPresetsPresetIdPutBodyTeachingLanguageDefault = `en`;
export const updatePresetApiPresetsPresetIdPutBodyTeachingLanguageMin = 2;
export const updatePresetApiPresetsPresetIdPutBodyTeachingLanguageMax = 10;

export const updatePresetApiPresetsPresetIdPutBodyClassSizeOneExclusiveMin = 0;

export const updatePresetApiPresetsPresetIdPutBodyEalDStudentsOneMin = 0;

export const updatePresetApiPresetsPresetIdPutBodyReadingSupportStudentsOneMin = 0;

export const updatePresetApiPresetsPresetIdPutBodyExtensionStudentsOneMin = 0;

export const updatePresetApiPresetsPresetIdPutBodyAverageReadingLevelOneMax = 50;

export const updatePresetApiPresetsPresetIdPutBodySourceWeightsDdgsDefault = 0.34;
export const updatePresetApiPresetsPresetIdPutBodySourceWeightsDdgsMin = 0;
export const updatePresetApiPresetsPresetIdPutBodySourceWeightsDdgsMax = 1;

export const updatePresetApiPresetsPresetIdPutBodySourceWeightsYoutubeDefault = 0.33;
export const updatePresetApiPresetsPresetIdPutBodySourceWeightsYoutubeMin = 0;
export const updatePresetApiPresetsPresetIdPutBodySourceWeightsYoutubeMax = 1;

export const updatePresetApiPresetsPresetIdPutBodySourceWeightsOpenalexDefault = 0.33;
export const updatePresetApiPresetsPresetIdPutBodySourceWeightsOpenalexMin = 0;
export const updatePresetApiPresetsPresetIdPutBodySourceWeightsOpenalexMax = 1;



export const UpdatePresetApiPresetsPresetIdPutBody = zod.object({
  "name": zod.string().min(1).max(updatePresetApiPresetsPresetIdPutBodyNameMax),
  "is_default": zod.boolean().default(updatePresetApiPresetsPresetIdPutBodyIsDefaultDefault),
  "curriculum_framework": zod.union([zod.string().max(updatePresetApiPresetsPresetIdPutBodyCurriculumFrameworkOneMax),zod.null()]).optional(),
  "subject": zod.string().min(1).max(updatePresetApiPresetsPresetIdPutBodySubjectMax),
  "year_level": zod.string().min(1).max(updatePresetApiPresetsPresetIdPutBodyYearLevelMax),
  "country": zod.string().min(1).max(updatePresetApiPresetsPresetIdPutBodyCountryMax),
  "state_region": zod.union([zod.string().max(updatePresetApiPresetsPresetIdPutBodyStateRegionOneMax),zod.null()]).optional(),
  "city": zod.union([zod.string().max(updatePresetApiPresetsPresetIdPutBodyCityOneMax),zod.null()]).optional(),
  "teaching_language": zod.string().min(updatePresetApiPresetsPresetIdPutBodyTeachingLanguageMin).max(updatePresetApiPresetsPresetIdPutBodyTeachingLanguageMax).default(updatePresetApiPresetsPresetIdPutBodyTeachingLanguageDefault),
  "class_size": zod.union([zod.number().gt(updatePresetApiPresetsPresetIdPutBodyClassSizeOneExclusiveMin),zod.null()]).optional(),
  "eal_d_students": zod.union([zod.number().min(updatePresetApiPresetsPresetIdPutBodyEalDStudentsOneMin),zod.null()]).optional(),
  "reading_support_students": zod.union([zod.number().min(updatePresetApiPresetsPresetIdPutBodyReadingSupportStudentsOneMin),zod.null()]).optional(),
  "extension_students": zod.union([zod.number().min(updatePresetApiPresetsPresetIdPutBodyExtensionStudentsOneMin),zod.null()]).optional(),
  "student_interests": zod.array(zod.string()).optional(),
  "language_backgrounds": zod.array(zod.string()).optional(),
  "average_reading_level": zod.union([zod.string().max(updatePresetApiPresetsPresetIdPutBodyAverageReadingLevelOneMax),zod.null()]).optional(),
  "source_weights": zod.object({
  "ddgs": zod.number().min(updatePresetApiPresetsPresetIdPutBodySourceWeightsDdgsMin).max(updatePresetApiPresetsPresetIdPutBodySourceWeightsDdgsMax).default(updatePresetApiPresetsPresetIdPutBodySourceWeightsDdgsDefault),
  "youtube": zod.number().min(updatePresetApiPresetsPresetIdPutBodySourceWeightsYoutubeMin).max(updatePresetApiPresetsPresetIdPutBodySourceWeightsYoutubeMax).default(updatePresetApiPresetsPresetIdPutBodySourceWeightsYoutubeDefault),
  "openalex": zod.number().min(updatePresetApiPresetsPresetIdPutBodySourceWeightsOpenalexMin).max(updatePresetApiPresetsPresetIdPutBodySourceWeightsOpenalexMax).default(updatePresetApiPresetsPresetIdPutBodySourceWeightsOpenalexDefault)
}).optional().describe('Source weights for federated search result distribution.'),
  "additional_notes": zod.union([zod.string(),zod.null()]).optional()
}).describe('Schema for updating a classroom preset (full replacement).')

export const UpdatePresetApiPresetsPresetIdPutResponse = zod.object({
  "id": zod.uuid(),
  "user_id": zod.uuid(),
  "is_default": zod.boolean(),
  "name": zod.string(),
  "curriculum_framework": zod.union([zod.string(),zod.null()]),
  "subject": zod.string(),
  "year_level": zod.string(),
  "country": zod.string(),
  "state_region": zod.union([zod.string(),zod.null()]),
  "city": zod.union([zod.string(),zod.null()]),
  "teaching_language": zod.string(),
  "class_size": zod.union([zod.number(),zod.null()]),
  "eal_d_students": zod.union([zod.number(),zod.null()]),
  "reading_support_students": zod.union([zod.number(),zod.null()]),
  "extension_students": zod.union([zod.number(),zod.null()]),
  "student_interests": zod.array(zod.unknown()),
  "language_backgrounds": zod.array(zod.unknown()),
  "average_reading_level": zod.union([zod.string(),zod.null()]),
  "source_weights": zod.record(zod.string(), zod.unknown()),
  "additional_notes": zod.union([zod.string(),zod.null()]),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('Schema for preset response including id and timestamps.')

/**
 * Delete a classroom preset. Returns 409 if it is the default.
 * @summary Delete Preset
 */
export const DeletePresetApiPresetsPresetIdDeleteParams = zod.object({
  "preset_id": zod.uuid()
})

/**
 * Set a classroom preset as the default (atomic swap).
 * @summary Set Default Preset
 */
export const SetDefaultPresetApiPresetsPresetIdDefaultPatchParams = zod.object({
  "preset_id": zod.uuid()
})

export const SetDefaultPresetApiPresetsPresetIdDefaultPatchResponse = zod.object({
  "id": zod.uuid(),
  "is_default": zod.boolean()
}).describe('Minimal response after setting a preset as default.')

